// Class: ReadtZq
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::tZq
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : ntonon
Date           : Fri Jan 17 12:05:41 2020
Host           : Linux cmspcx36679 4.15.0-1065-oem #75-Ubuntu SMP Wed Nov 20 10:51:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ntonon/Postdoc/EFTSimulations/myAnalysis
Training events: 285036
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
DoBoostMonitor: "True" [Create control plot with ROC integral vs tree number]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
metEt                         metEt                         metEt                         metEt                                                           'F'    [0.088276386261,1124.21179199]
maxEtaJet                     maxEtaJet                     maxEtaJet                     maxEtaJet                                                       'F'    [0.00506666116416,4.90954637527]
leptonCharge                  leptonCharge                  leptonCharge                  leptonCharge                                                    'F'    [-1,1]
maxDijetDelR                  maxDijetDelR                  maxDijetDelR                  maxDijetDelR                                                    'F'    [0.398503094912,9.7253036499]
deepCSV_2nd                   deepCSV_2nd                   deepCSV_2nd                   deepCSV_2nd                                                     'F'    [-9,0.999997794628]
dEtaFwdJetBJet                dEtaFwdJetBJet                dEtaFwdJetBJet                dEtaFwdJetBJet                                                  'F'    [0,6.84299087524]
dEtaFwdJetClosestLep          dEtaFwdJetClosestLep          dEtaFwdJetClosestLep          dEtaFwdJetClosestLep                                            'F'    [1.19209289551e-07,5.60153913498]
mHT                           mHT                           mHT                           mHT                                                             'F'    [125.129852295,3658.28320312]
Mass_3l                       Mass_3l                       Mass_3l                       Mass_3l                                                         'F'    [81.0126037598,1871.6619873]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new tZqNode

#ifndef tZqNode__def
#define tZqNode__def

class tZqNode {

public:

   // constructor of an essentially "empty" node floating in space
   tZqNode ( tZqNode* left,tZqNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~tZqNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   tZqNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   tZqNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   tZqNode*   fLeft;     // pointer to the left daughter node
   tZqNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   tZqNode::~tZqNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool tZqNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool tZqNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadtZq : public IClassifierReader {

 public:

   // constructor
   ReadtZq( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadtZq" ),
        fNvars( 9 )
   {
      // the training input variables
      const char* inputVars[] = { "metEt", "maxEtaJet", "leptonCharge", "maxDijetDelR", "deepCSV_2nd", "dEtaFwdJetBJet", "dEtaFwdJetClosestLep", "mHT", "Mass_3l" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadtZq() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<tZqNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadtZq::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      tZqNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(tZqNode*)current->GetRight();
         else current=(tZqNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadtZq::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310878,-0.0378243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505523,0.00110466) , 
1, 2.34824, 1, 0, 0.347611,-0.152389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667709,0.0335417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473267,-0.00534663) , 
7, 600.405, 1, 0, 0.613078,0.113078) , 
3, 3.55384, 1, 0, 0.5,-5.77655e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3069,-0.0351591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49134,-0.00115492) , 
1, 2.15499, 1, 0, 0.35592,-0.130427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564901,0.0107278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766529,0.051083) , 
6, 0.863919, 1, 0, 0.619348,0.108037) , 
3, 3.64664, 1, 0, 0.5,-5.28785e-07)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307287,-0.0336575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51661,0.00528582) , 
5, 1.60716, 1, 0, 0.363267,-0.115703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563494,0.00998934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733381,0.0412018) , 
6, 0.585236, 1, 0, 0.620282,0.101779) , 
1, 2.2987, 1, 0, 0.5,-1.84651e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455968,-0.0041317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313873,-0.0320648) , 
7, 406.376, 1, 0, 0.382846,-0.0918975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688408,0.0309204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475195,-0.00802546) , 
7, 658.039, 1, 0, 0.641065,0.110649) , 
3, 3.97146, 1, 0, 0.5,-2.50126e-06)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405988,-0.0111039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248739,-0.0394634) , 
7, 476.687, 1, 0, 0.347611,-0.106773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536204,0.00217113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712394,0.0338956) , 
5, 1.63415, 1, 0, 0.613078,0.0792327) , 
3, 3.55384, 1, 0, 0.5,1.85808e-06)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319999,-0.0259824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526204,0.00554699) , 
5, 1.57992, 1, 0, 0.380545,-0.0821901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570055,0.00832194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762829,0.0398517) , 
6, 0.585236, 1, 0, 0.633255,0.0916836) , 
1, 2.46951, 1, 0, 0.5,-6.72342e-07)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306459,-0.0250332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517476,0.0046764) , 
5, 1.7706, 1, 0, 0.35245,-0.0904358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645173,0.0197378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459543,-0.0124369) , 
7, 668.274, 1, 0, 0.61188,0.0685798) , 
1, 2.2011, 1, 0, 0.5,3.94827e-06)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465564,0.00109411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319864,-0.0247623) , 
4, 0.0547244, 1, 0, 0.382846,-0.0662433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718022,0.0293784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545415,0.000222) , 
7, 490.543, 1, 0, 0.641065,0.0797582) , 
3, 3.97146, 1, 0, 0.5,-2.53767e-06)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378766,-0.0109695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205887,-0.0396874) , 
7, 599.733, 1, 0, 0.341266,-0.0827934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527741,-0.000240531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.7045,0.0263107) , 
5, 1.63415, 1, 0, 0.604167,0.054337) , 
3, 3.46103, 1, 0, 0.5,2.8087e-06)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263713,-0.0279988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440693,-0.00447659) , 
1, 1.42732, 1, 0, 0.380545,-0.059745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562106,0.00295341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737472,0.029954) , 
6, 0.33442, 1, 0, 0.633255,0.0666466) , 
1, 2.46951, 1, 0, 0.5,-1.61756e-07)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376497,-0.017391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530748,0.00695044) , 
6, 0.17131, 1, 0, 0.446527,-0.0308927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801168,0.0439041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598302,0.00526166) , 
7, 405.56, 1, 0, 0.691799,0.110814) , 
1, 3.27472, 1, 0, 0.5,1.46802e-06)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357291,-0.00930681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220783,-0.0328328) , 
7, 413.278, 1, 0, 0.285459,-0.101393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597932,0.0114917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40925,-0.0166133) , 
7, 670.044, 1, 0, 0.561744,0.0291987) , 
1, 1.59109, 1, 0, 0.5,1.41919e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226165,-0.0355295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42093,-0.00499639) , 
3, 2.00526, 1, 0, 0.394171,-0.0438077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730358,0.0251865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546781,-0.00187199) , 
7, 490.543, 1, 0, 0.64753,0.0610685) , 
3, 4.11066, 1, 0, 0.5,-4.04334e-07)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526824,0.00873349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350677,-0.0207099) , 
7, 406.376, 1, 0, 0.428371,-0.0366336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465085,-0.0124383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731074,0.030374) , 
6, 0.0836053, 1, 0, 0.633802,0.0684426) , 
5, 1.6001, 1, 0, 0.5,4.13145e-06)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376497,-0.0145845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530748,0.00599502) , 
6, 0.17131, 1, 0, 0.446527,-0.0252229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776743,0.0324319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557357,-0.00078253) , 
7, 479.66, 1, 0, 0.691799,0.090532) , 
1, 3.27472, 1, 0, 0.5,1.34092e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533773,0.00938526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358832,-0.0176979) , 
7, 388.798, 1, 0, 0.429596,-0.0317639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463384,-0.0109655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734618,0.0274292) , 
6, 0.0836053, 1, 0, 0.636483,0.0616473) , 
5, 1.63415, 1, 0, 0.5,2.41535e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344509,-0.00484007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208996,-0.0311387) , 
4, 0.0547244, 1, 0, 0.263474,-0.092852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576311,0.00764408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36929,-0.0199133) , 
7, 775.511, 1, 0, 0.550864,0.0200054) , 
1, 1.42029, 1, 0, 0.5,3.12474e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0306596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574216,0.00859363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387451,-0.0134425) , 
7, 599.733, 1, 0, 0.523921,0.0124111) , 
3, 2.02257, 1, 0, 0.5,1.40125e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376497,-0.0124636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530748,0.00503632) , 
6, 0.17131, 1, 0, 0.446527,-0.0215074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801168,0.0325502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598302,0.00397452) , 
7, 405.56, 1, 0, 0.691799,0.0771571) , 
1, 3.27472, 1, 0, 0.5,2.92707e-06)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480225,0.00415955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341121,-0.0149268) , 
4, 0.0547244, 1, 0, 0.401005,-0.0310681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578303,0.00142953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.768179,0.0254718) , 
6, 0.473762, 1, 0, 0.651978,0.0477311) , 
3, 4.20347, 1, 0, 0.5,1.37597e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477474,0.00133055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742773,0.0250108) , 
1, 3.27472, 1, 0, 0.538752,0.0309764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35566,-0.0198638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570495,0.0049758) , 
5, 1.25694, 1, 0, 0.442834,-0.0456469) , 
2, -0.99005, 1, 0, 0.5,1.93699e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0267541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574216,0.00758441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387451,-0.0120661) , 
7, 599.733, 1, 0, 0.523921,0.0105503) , 
3, 2.02257, 1, 0, 0.5,2.29145e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477474,0.00128688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742773,0.0225917) , 
1, 3.27472, 1, 0, 0.538752,0.0278963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38166,-0.0148251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649966,0.0117164) , 
5, 2.03828, 1, 0, 0.442834,-0.0411209) , 
2, -0.99005, 1, 0, 0.5,1.22887e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519291,0.0042882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362722,-0.0153613) , 
7, 387.941, 1, 0, 0.434182,-0.0295156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445908,-0.0036623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744735,0.0230395) , 
5, 1.63415, 1, 0, 0.583503,0.0374862) , 
6, 0.195079, 1, 0, 0.5,1.76457e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379307,-0.00363592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210963,-0.0250948) , 
7, 459.11, 1, 0, 0.318525,-0.0494616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596681,0.00683059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359502,-0.0177826) , 
7, 845.518, 1, 0, 0.572544,0.0198067) , 
3, 3.13622, 1, 0, 0.5,2.46402e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477474,0.00123867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742773,0.0201965) , 
1, 3.27472, 1, 0, 0.538752,0.0248092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534988,0.00398149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381444,-0.016063) , 
7, 388.798, 1, 0, 0.442834,-0.0365663) , 
2, -0.99005, 1, 0, 0.5,1.25109e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51896,0.00318036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360717,-0.0139312) , 
7, 387.941, 1, 0, 0.433531,-0.0276401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433211,-0.00527433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703428,0.0186074) , 
5, 1.22561, 1, 0, 0.579311,0.0330156) , 
6, 0.16721, 1, 0, 0.5,1.6065e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0230077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603475,0.0106666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468758,-0.00414313) , 
4, 0.0547244, 1, 0, 0.523921,0.00877823) , 
3, 2.02257, 1, 0, 0.5,1.91132e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420123,-0.0187053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561311,0.007142) , 
7, 250.272, 1, 0, 0.542034,0.0161123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313009,-0.0161068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622391,0.0106021) , 
5, 2.12321, 1, 0, 0.378009,-0.046711) , 
7, 599.733, 1, 0, 0.5,1.27575e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609306,0.0128992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486616,-0.000981222) , 
4, 0.0547244, 1, 0, 0.538752,0.0220966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394853,-0.0114623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637382,0.0113618) , 
6, 0.791295, 1, 0, 0.442834,-0.0325769) , 
2, -0.99005, 1, 0, 0.5,7.64711e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344509,-0.000552131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208996,-0.0227676) , 
4, 0.0547244, 1, 0, 0.263474,-0.0574338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480456,-0.00367323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615315,0.00883398) , 
6, 0.0836052, 1, 0, 0.550864,0.01236) , 
1, 1.42029, 1, 0, 0.5,7.462e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0204543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57568,0.00567859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395891,-0.00824983) , 
7, 582.155, 1, 0, 0.523921,0.00760728) , 
3, 2.02257, 1, 0, 0.5,-3.30625e-08)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429737,-0.0133667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487207,0.00133094) , 
0, 33.6442, 1, 0, 0.474628,-0.00859569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762865,0.0278301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683438,0.006988) , 
1, 3.78398, 1, 0, 0.723381,0.0756271) , 
3, 5.82754, 1, 0, 0.5,-5.34937e-06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421743,-0.0162871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530959,0.00406701) , 
7, 250.623, 1, 0, 0.518686,0.0078111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313908,-0.0174993) , 
7, 845.823, 1, 0, 0.5,-3.6638e-07)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477474,0.00098141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742773,0.0167126) , 
1, 3.27472, 1, 0, 0.538752,0.0197524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534988,0.00398519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381444,-0.0136119) , 
7, 388.798, 1, 0, 0.442834,-0.0291446) , 
2, -0.99005, 1, 0, 0.5,-2.80847e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51896,0.00308441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360717,-0.0116755) , 
7, 387.941, 1, 0, 0.433531,-0.0217964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433211,-0.0044762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703428,0.0153018) , 
5, 1.22561, 1, 0, 0.579311,0.026009) , 
6, 0.16721, 1, 0, 0.5,6.23533e-07)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472015,0.0030086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334665,-0.0100271) , 
4, 0.0547244, 1, 0, 0.394171,-0.0191394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730358,0.0129342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546781,-0.00160178) , 
7, 490.543, 1, 0, 0.64753,0.0266901) , 
3, 4.11066, 1, 0, 0.5,3.80579e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417895,-0.019027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577025,0.00798727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454726,-0.00344359) , 
4, 0.0547244, 1, 0, 0.505771,0.00596852) , 
0, 16.8662, 1, 0, 0.5,5.42646e-06)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0181067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458015,-0.00398788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583351,0.0066387) , 
6, 0.0836052, 1, 0, 0.523921,0.00658308) , 
3, 2.02257, 1, 0, 0.5,5.48232e-06)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324386,-0.00729628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588708,0.00653227) , 
3, 2.86054, 1, 0, 0.538752,0.0175382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35566,-0.0123198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570495,0.00367579) , 
5, 1.25694, 1, 0, 0.442834,-0.0258678) , 
2, -0.99005, 1, 0, 0.5,1.48325e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421743,-0.0152721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530959,0.00368849) , 
7, 250.623, 1, 0, 0.518686,0.00671713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313908,-0.0153473) , 
7, 845.823, 1, 0, 0.5,-9.10141e-07)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450019,-0.00671992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49768,0.00406393) , 
0, 61.6075, 1, 0, 0.472581,-0.00724605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77513,0.0258093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661917,0.00228022) , 
0, 63.6808, 1, 0, 0.716756,0.0572572) , 
3, 5.73473, 1, 0, 0.5,-2.93e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435851,-0.0117956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585003,0.00799541) , 
7, 258.056, 1, 0, 0.554517,0.0171679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368114,-0.00960609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714777,0.0167709) , 
5, 2.47655, 1, 0, 0.425381,-0.0234943) , 
7, 476.687, 1, 0, 0.5,1.58383e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417895,-0.0167071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546249,0.0051056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425741,-0.00658338) , 
8, 214.643, 1, 0, 0.505771,0.00519406) , 
0, 16.8662, 1, 0, 0.5,2.29002e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631916,0.0117931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496392,-0.00011358) , 
4, -1.98508, 1, 0, 0.538752,0.0156629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534988,0.00371434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381444,-0.0113762) , 
7, 388.798, 1, 0, 0.442834,-0.0231009) , 
2, -0.99005, 1, 0, 0.5,1.69969e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435702,-0.00168212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436037,-0.0193533) , 
5, 2.18506, 1, 0, 0.435751,-0.0196515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424684,-0.00317432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707082,0.0129092) , 
5, 1.36179, 1, 0, 0.560346,0.0184603) , 
6, 0.0836052, 1, 0, 0.5,1.44347e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0154751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.0137178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.00074802) , 
4, -8.95025, 1, 0, 0.523921,0.00547969) , 
3, 2.02257, 1, 0, 0.5,6.33143e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451358,-0.00607905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500552,0.00384047) , 
0, 61.6075, 1, 0, 0.474628,-0.00617788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762865,0.0231859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683438,0.00319339) , 
1, 3.78398, 1, 0, 0.723381,0.054426) , 
3, 5.82754, 1, 0, 0.5,3.44295e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421743,-0.0126057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530959,0.00310761) , 
7, 250.623, 1, 0, 0.518686,0.00572079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313908,-0.0132862) , 
7, 845.823, 1, 0, 0.5,6.12537e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344509,0.00123965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208996,-0.0172083) , 
4, 0.0547244, 1, 0, 0.263474,-0.0377828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561852,0.00303753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400976,-0.0149169) , 
0, 162.275, 1, 0, 0.550864,0.00812956) , 
1, 1.42029, 1, 0, 0.5,3.73135e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417895,-0.0150147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57574,0.00668634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451694,-0.00333578) , 
7, 406.376, 1, 0, 0.505771,0.00462415) , 
0, 16.8662, 1, 0, 0.5,-1.99053e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518442,0.00274349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366258,-0.00985391) , 
7, 377.394, 1, 0, 0.435751,-0.0178855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424684,-0.0025209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707082,0.0114441) , 
5, 1.36179, 1, 0, 0.560346,0.0167958) , 
6, 0.0836052, 1, 0, 0.5,-1.558e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395249,-0.012739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462806,-8.6657e-05) , 
7, 265.753, 1, 0, 0.453637,-0.00820175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827722,0.0256543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62968,0.000116487) , 
7, 361.1, 1, 0, 0.700262,0.03543) , 
1, 3.37232, 1, 0, 0.5,5.62398e-07)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550976,0.00479907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42748,-0.0113585) , 
4, 0.800993, 1, 0, 0.538752,0.0137978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355225,-0.0102274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553907,0.0023862) , 
5, 1.15502, 1, 0, 0.442834,-0.0203361) , 
2, -0.99005, 1, 0, 0.5,7.15037e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432995,-0.00930629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489385,0.00114775) , 
0, 33.6442, 1, 0, 0.477074,-0.00502396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724846,0.0122325) , 
3, 5.92034, 1, 0, 0.5,4.78172e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446224,-0.00832054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523039,0.00305125) , 
0, 30.3593, 1, 0, 0.50803,0.0035938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349323,-0.0156063) , 
0, 179.053, 1, 0, 0.5,5.63897e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435702,-0.000995968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436037,-0.017857) , 
5, 2.18506, 1, 0, 0.435751,-0.0158896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424684,-0.00202779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707082,0.0100259) , 
5, 1.36179, 1, 0, 0.560346,0.0149322) , 
6, 0.0836052, 1, 0, 0.5,4.12989e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409263,-0.0132418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544987,0.00331739) , 
7, 238.991, 1, 0, 0.532062,0.00741777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411466,-0.00195331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287176,-0.0161568) , 
2, -0.99005, 1, 0, 0.361989,-0.0318935) , 
7, 670.044, 1, 0, 0.5,6.90159e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0128941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.0120234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.000737784) , 
4, -8.95025, 1, 0, 0.523921,0.00443202) , 
3, 2.02257, 1, 0, 0.5,3.92101e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480225,0.00246167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341121,-0.00682608) , 
4, 0.0547244, 1, 0, 0.401005,-0.0118685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641444,0.0126291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655598,0.00118277) , 
1, 2.7507, 1, 0, 0.651978,0.0182259) , 
3, 4.20347, 1, 0, 0.5,2.06683e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496885,-0.0105956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54396,0.00464073) , 
8, 118.908, 1, 0, 0.536927,0.010239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366216,-0.00802045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616606,0.00540912) , 
3, 4.91956, 1, 0, 0.426314,-0.0204277) , 
8, 214.643, 1, 0, 0.5,1.35625e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550976,0.00420268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42748,-0.0101237) , 
4, 0.800993, 1, 0, 0.538752,0.0119139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534988,0.00351684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381444,-0.00931773) , 
7, 388.798, 1, 0, 0.442834,-0.0175731) , 
2, -0.99005, 1, 0, 0.5,6.65437e-07)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417895,-0.0121518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57574,0.00543808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451694,-0.00271834) , 
7, 406.376, 1, 0, 0.505771,0.0036901) , 
0, 16.8662, 1, 0, 0.5,-5.21804e-07)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436017,-0.000744985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434382,-0.015733) , 
5, 2.09108, 1, 0, 0.435751,-0.0146025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495653,0.000102238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762902,0.0144679) , 
3, 4.92599, 1, 0, 0.560346,0.0137146) , 
6, 0.0836052, 1, 0, 0.5,-3.73448e-07)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0118303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.0104291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.000588657) , 
4, -8.95025, 1, 0, 0.523921,0.00401641) , 
3, 2.02257, 1, 0, 0.5,3.39576e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411678,-0.0126805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516322,0.00190359) , 
7, 238.336, 1, 0, 0.50803,0.00308036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349323,-0.0136154) , 
0, 179.053, 1, 0, 0.5,1.81202e-06)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445427,-0.000329803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557108,-0.0158531) , 
1, 3.20477, 1, 0, 0.453637,-0.00636197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827722,0.0226194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62968,-0.00080105) , 
7, 361.1, 1, 0, 0.700262,0.0274838) , 
1, 3.37232, 1, 0, 0.5,6.83959e-07)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344509,0.00149504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208996,-0.0137911) , 
4, 0.0547244, 1, 0, 0.263474,-0.0281082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561561,0.00258331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448893,-0.00987583) , 
4, 0.800991, 1, 0, 0.550864,0.00605398) , 
1, 1.42029, 1, 0, 0.5,7.76025e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532248,0.0115427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540045,0.000668581) , 
5, 0.170224, 1, 0, 0.538752,0.0107251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399001,-0.00585501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713655,0.0109411) , 
5, 2.58182, 1, 0, 0.442834,-0.015812) , 
2, -0.99005, 1, 0, 0.5,3.66991e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421743,-0.0101382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530959,0.0023859) , 
7, 250.623, 1, 0, 0.518686,0.00406934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313908,-0.00980492) , 
7, 845.823, 1, 0, 0.5,3.30079e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449313,-0.000497964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386134,-0.0188167) , 
6, 0.0115069, 1, 0, 0.439881,-0.0146032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60213,0.00722842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479966,-0.00252181) , 
4, 0.104473, 1, 0, 0.544612,0.0108397) , 
6, 0.0278685, 1, 0, 0.5,1.85632e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45442,-0.00464026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502207,0.00323249) , 
0, 61.6075, 1, 0, 0.477074,-0.00396948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724846,0.00994298) , 
3, 5.92034, 1, 0, 0.5,1.90309e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483433,-0.000452664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752356,0.0138311) , 
3, 5.88604, 1, 0, 0.50887,0.0032707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.0109462) , 
0, 162.275, 1, 0, 0.5,2.59872e-06)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417895,-0.0106331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56347,0.0068495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483109,-0.00167493) , 
7, 336.064, 1, 0, 0.505771,0.00320376) , 
0, 16.8662, 1, 0, 0.5,4.11755e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396005,0.00589031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284527,-0.00942301) , 
7, 300.909, 1, 0, 0.318525,-0.0188361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587625,0.00323105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443548,-0.0107002) , 
4, 0.800991, 1, 0, 0.572544,0.00753496) , 
3, 3.13622, 1, 0, 0.5,3.73726e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523208,-0.0094539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540438,0.00352864) , 
8, 118.456, 1, 0, 0.538752,0.00967838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394853,-0.00583157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637382,0.00770108) , 
6, 0.791295, 1, 0, 0.442834,-0.0142745) , 
2, -0.99005, 1, 0, 0.5,1.024e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438631,-0.00856939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556628,0.00406718) , 
7, 259.33, 1, 0, 0.536927,0.00810329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240337,-0.0134629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49277,-0.000730811) , 
3, 3.07575, 1, 0, 0.426314,-0.0161671) , 
8, 214.643, 1, 0, 0.5,9.44793e-07)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407446,-0.0107217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533644,0.00211891) , 
7, 238.38, 1, 0, 0.522698,0.00417477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374449,-0.00125215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301305,-0.0125399) , 
4, 0.154219, 1, 0, 0.334638,-0.0304264) , 
7, 775.511, 1, 0, 0.5,-1.41993e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552205,0.0082695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611163,-0.0212918) , 
5, 2.48527, 1, 0, 0.563917,0.0135665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413578,-0.0046197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791803,0.0196082) , 
5, 2.89849, 1, 0, 0.456449,-0.00924796) , 
7, 388.798, 1, 0, 0.5,-2.58967e-06)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.0100199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.00954824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.000626235) , 
4, -8.95025, 1, 0, 0.523921,0.00332708) , 
3, 2.02257, 1, 0, 0.5,5.41031e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449313,-0.000402339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386134,-0.0168464) , 
6, 0.0115069, 1, 0, 0.439881,-0.0128201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415371,-0.002508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649995,0.00643985) , 
5, 0.987297, 1, 0, 0.544612,0.00952039) , 
6, 0.0278685, 1, 0, 0.5,4.07046e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417895,-0.0095578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56347,0.00617687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483109,-0.00152265) , 
7, 336.064, 1, 0, 0.505771,0.00286141) , 
0, 16.8662, 1, 0, 0.5,4.1397e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483934,0.00563662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60148,-0.00227171) , 
5, 1.2937, 1, 0, 0.538752,0.00876288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534988,0.00283905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381444,-0.00716635) , 
7, 388.798, 1, 0, 0.442834,-0.0129173) , 
2, -0.99005, 1, 0, 0.5,3.75784e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22042,-0.0139779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293906,0.00160354) , 
0, 57.9001, 1, 0, 0.25357,-0.0263209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467043,-0.0019182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607085,0.00388691) , 
6, 0.0836052, 1, 0, 0.539555,0.00422761) , 
1, 1.27389, 1, 0, 0.5,2.4301e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483433,-0.000417406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752356,0.0123759) , 
3, 5.88604, 1, 0, 0.50887,0.00280883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00954144) , 
0, 162.275, 1, 0, 0.5,1.75995e-07)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40055,0.0020664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566022,-0.0158027) , 
1, 2.85253, 1, 0, 0.461144,-0.0193204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595088,0.00738145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45254,-0.00297212) , 
4, 0.0547244, 1, 0, 0.510661,0.00530296) , 
0, 33.6442, 1, 0, 0.5,1.59022e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00921605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.0079616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.00044784) , 
4, -8.95025, 1, 0, 0.523921,0.0030271) , 
3, 2.02257, 1, 0, 0.5,3.92039e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305691,-0.0082773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37192,0.00166549) , 
6, 0.0244729, 1, 0, 0.341266,-0.0123325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595646,-0.00994973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605509,0.00375669) , 
7, 285.261, 1, 0, 0.604167,0.00809771) , 
3, 3.46103, 1, 0, 0.5,2.80548e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420123,-0.00832829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561311,0.00294336) , 
7, 250.272, 1, 0, 0.542034,0.00576521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309652,-0.00701762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608628,0.00545026) , 
5, 2.03474, 1, 0, 0.378009,-0.016723) , 
7, 599.733, 1, 0, 0.5,2.24395e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542243,0.00977478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567124,-0.0170893) , 
5, 2.07673, 1, 0, 0.548527,0.0152399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386519,-0.00476447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653479,0.00490341) , 
5, 1.60977, 1, 0, 0.480385,-0.00615863) , 
7, 336.064, 1, 0, 0.5,9.73145e-07)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501673,0.00391911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669726,-0.0062481) , 
5, 2.38313, 1, 0, 0.538752,0.0081042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352364,-0.00713478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544209,0.00191071) , 
5, 1.05311, 1, 0, 0.442834,-0.011949) , 
2, -0.99005, 1, 0, 0.5,2.38659e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446224,-0.00591638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523039,0.00208279) , 
0, 30.3593, 1, 0, 0.50803,0.00216733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349323,-0.00989854) , 
0, 179.053, 1, 0, 0.5,1.83634e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568157,0.0129505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394309,-0.00443172) , 
7, 412.95, 1, 0, 0.496698,0.0248524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497574,-0.0106142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500732,3.67312e-05) , 
8, 116.647, 1, 0, 0.500472,-0.00355434) , 
5, 0.0340447, 1, 0, 0.5,1.17011e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436296,0.00555211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309658,-0.00578038) , 
4, -8.95025, 1, 0, 0.341266,-0.0115692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595646,-0.0086056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605509,0.00343022) , 
7, 285.261, 1, 0, 0.604167,0.00759437) , 
3, 3.46103, 1, 0, 0.5,1.33005e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542243,0.00885216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567124,-0.0145806) , 
5, 2.07673, 1, 0, 0.548527,0.0145213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439753,-0.00289297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785139,0.0120395) , 
5, 2.91771, 1, 0, 0.480385,-0.00586845) , 
7, 336.064, 1, 0, 0.5,7.8024e-07)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328758,-0.000812583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249109,-0.0108151) , 
8, 172.604, 1, 0, 0.288132,-0.022836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647829,0.00968112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521194,-0.000278504) , 
4, -8.95025, 1, 0, 0.536511,0.0039395) , 
3, 2.6258, 1, 0, 0.5,3.59689e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514926,0.00315097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700446,-0.00998443) , 
5, 2.99594, 1, 0, 0.538752,0.00743917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534988,0.00243763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381444,-0.00618946) , 
7, 388.798, 1, 0, 0.442834,-0.0109673) , 
2, -0.99005, 1, 0, 0.5,2.67915e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385504,-0.017614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505676,0.00189457) , 
7, 272.165, 1, 0, 0.482489,-0.00858529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645302,0.022417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500688,-0.000762957) , 
7, 287.292, 1, 0, 0.518955,0.00929936) , 
0, 61.6075, 1, 0, 0.5,2.93644e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00813364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547881,0.00744993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520799,-0.000301385) , 
5, 0.0340447, 1, 0, 0.523921,0.00262946) , 
3, 2.02257, 1, 0, 0.5,2.68972e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434849,-0.00682542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531161,0.00180043) , 
7, 257.794, 1, 0, 0.518686,0.00272691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313908,-0.00680715) , 
7, 845.823, 1, 0, 0.5,1.6143e-06)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542243,0.00802808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567124,-0.0128391) , 
5, 2.07673, 1, 0, 0.548527,0.0134129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54116,0.0108238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47314,-0.0027176) , 
4, -8.95025, 1, 0, 0.480385,-0.00542025) , 
7, 336.064, 1, 0, 0.5,9.0113e-07)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305691,-0.00737425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37192,0.00143365) , 
6, 0.0244729, 1, 0, 0.341266,-0.0109453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595646,-0.00777551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605509,0.00319908) , 
7, 285.261, 1, 0, 0.604167,0.00718539) , 
3, 3.46103, 1, 0, 0.5,1.61695e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430835,-0.0114999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588745,0.00824925) , 
0, 32.181, 1, 0, 0.548527,0.0136159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439753,-0.0027117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785139,0.0112888) , 
5, 2.91771, 1, 0, 0.480385,-0.00550213) , 
7, 336.064, 1, 0, 0.5,1.02819e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514926,0.00293179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700446,-0.009397) , 
5, 2.99594, 1, 0, 0.538752,0.00683852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352364,-0.0064596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544209,0.00203708) , 
5, 1.05311, 1, 0, 0.442834,-0.010081) , 
2, -0.99005, 1, 0, 0.5,2.78023e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496885,-0.00813672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54396,0.00308678) , 
8, 118.908, 1, 0, 0.536927,0.00585645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432499,-0.00707719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417157,0.00365949) , 
8, 297.082, 1, 0, 0.426314,-0.0116782) , 
8, 214.643, 1, 0, 0.5,2.7563e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348637,-0.000921773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217313,-0.0109425) , 
7, 355.774, 1, 0, 0.288132,-0.0199677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647829,0.00862059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521194,-0.000258833) , 
4, -8.95025, 1, 0, 0.536511,0.00344373) , 
3, 2.6258, 1, 0, 0.5,2.33558e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445427,0.000174229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557108,-0.014814) , 
1, 3.20477, 1, 0, 0.453637,-0.00395869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827722,0.0183844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62968,-0.00207685) , 
7, 361.1, 1, 0, 0.700262,0.0171069) , 
1, 3.37232, 1, 0, 0.5,1.42488e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492366,-0.000230052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772176,0.0142352) , 
3, 6.30107, 1, 0, 0.50887,0.0021514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00743797) , 
0, 162.275, 1, 0, 0.5,6.24777e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385504,-0.0153755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505676,0.00159984) , 
7, 272.165, 1, 0, 0.482489,-0.00761448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645302,0.0197399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500688,-0.000633444) , 
7, 287.292, 1, 0, 0.518955,0.00825678) , 
0, 61.6075, 1, 0, 0.5,6.91462e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22042,-0.0110991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293906,0.00170202) , 
0, 57.9001, 1, 0, 0.25357,-0.0192933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550223,0.0015659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438377,-0.00706239) , 
4, 0.800993, 1, 0, 0.539555,0.00310406) , 
1, 1.27389, 1, 0, 0.5,6.27762e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483934,0.0044794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60148,-0.00213673) , 
5, 1.2937, 1, 0, 0.538752,0.00623337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394853,-0.0040643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637382,0.00606974) , 
6, 0.791295, 1, 0, 0.442834,-0.00918505) , 
2, -0.99005, 1, 0, 0.5,4.08556e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00696545) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.00612845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.000368307) , 
4, -8.95025, 1, 0, 0.523921,0.00221592) , 
3, 2.02257, 1, 0, 0.5,3.50329e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435648,-0.00585542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548466,0.0020362) , 
7, 257.968, 1, 0, 0.532062,0.00356815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315187,-0.0121243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389081,0.000943257) , 
0, 56.0148, 1, 0, 0.361989,-0.0153445) , 
7, 670.044, 1, 0, 0.5,2.77737e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542243,0.00731015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567124,-0.0117078) , 
5, 2.07673, 1, 0, 0.548527,0.0120396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388312,-0.00380559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656214,0.00410252) , 
5, 1.64331, 1, 0, 0.480385,-0.00486424) , 
7, 336.064, 1, 0, 0.5,1.55345e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392056,0.00625389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330161,-0.00414839) , 
7, 265.753, 1, 0, 0.341266,-0.00905636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595646,-0.00745693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605509,0.00282135) , 
7, 285.261, 1, 0, 0.604167,0.00594656) , 
3, 3.46103, 1, 0, 0.5,2.06471e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483433,-0.000376037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752356,0.00981741) , 
3, 5.88604, 1, 0, 0.50887,0.00196963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00686136) , 
0, 162.275, 1, 0, 0.5,1.66107e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430835,-0.00974817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588745,0.00696717) , 
0, 32.181, 1, 0, 0.548527,0.0113559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54116,0.0096021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47314,-0.00235648) , 
4, -8.95025, 1, 0, 0.480385,-0.00458666) , 
7, 336.064, 1, 0, 0.5,2.4329e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439632,0.00207187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440357,-0.00929535) , 
5, 1.40972, 1, 0, 0.439881,-0.00848079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415371,-0.00264262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649995,0.00515813) , 
5, 0.987297, 1, 0, 0.544612,0.00629739) , 
6, 0.0278685, 1, 0, 0.5,2.36761e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568157,0.0102149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394309,-0.00323673) , 
7, 412.95, 1, 0, 0.496698,0.0197283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497574,-0.00864063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500732,4.42515e-05) , 
8, 116.647, 1, 0, 0.500472,-0.0028197) , 
5, 0.0340447, 1, 0, 0.5,2.51299e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514926,0.00259547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700446,-0.00870209) , 
5, 2.99594, 1, 0, 0.538752,0.00582537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355225,-0.00531684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553907,0.00196599) , 
5, 1.15502, 1, 0, 0.442834,-0.00858718) , 
2, -0.99005, 1, 0, 0.5,2.46943e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396005,0.00469361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284527,-0.00639908) , 
7, 300.909, 1, 0, 0.318525,-0.0111568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515034,0.00393239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641768,-0.00267954) , 
1, 2.8651, 1, 0, 0.572544,0.00446345) , 
3, 3.13622, 1, 0, 0.5,2.52978e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512163,0.00335545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417412,-0.00289662) , 
7, 336.064, 1, 0, 0.446555,-0.00381956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673828,0.0128131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676887,-0.000530175) , 
1, 3.08644, 1, 0, 0.676095,0.0125905) , 
3, 4.9459, 1, 0, 0.5,1.28299e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00655317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547881,0.00627545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520799,-0.000285135) , 
5, 0.0340447, 1, 0, 0.523921,0.00206766) , 
3, 2.02257, 1, 0, 0.5,1.78059e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415424,-0.00665341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520819,0.00107333) , 
7, 240.216, 1, 0, 0.511999,0.00166591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3045,-0.00690936) , 
7, 951.29, 1, 0, 0.5,1.10481e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445427,0.000230268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557108,-0.0130138) , 
1, 3.20477, 1, 0, 0.453637,-0.00318399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827722,0.0163631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62968,-0.00218731) , 
7, 361.1, 1, 0, 0.700262,0.0137561) , 
1, 3.37232, 1, 0, 0.5,5.62067e-07)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385504,-0.0137682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505676,0.00158154) , 
7, 272.165, 1, 0, 0.482489,-0.00629013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584263,0.00752076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444187,-0.00495479) , 
4, 0.104473, 1, 0, 0.518955,0.00681788) , 
0, 61.6075, 1, 0, 0.5,4.35341e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536637,-0.00420609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539438,0.00302326) , 
8, 135.979, 1, 0, 0.538752,0.00532164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425492,-0.00483634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465931,0.00203748) , 
0, 65.3505, 1, 0, 0.442834,-0.00784163) , 
2, -0.99005, 1, 0, 0.5,3.46751e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496885,-0.00647412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54396,0.00251036) , 
8, 118.908, 1, 0, 0.536927,0.00477701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432499,-0.00634272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417157,0.00377407) , 
8, 297.082, 1, 0, 0.426314,-0.00952329) , 
8, 214.643, 1, 0, 0.5,3.04912e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492366,-0.00019652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772176,0.0119613) , 
3, 6.30107, 1, 0, 0.50887,0.00173877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00608997) , 
0, 162.275, 1, 0, 0.5,2.53493e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43576,-0.00170692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539688,0.0025215) , 
6, 0.0718179, 1, 0, 0.487642,0.0014998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.00820338) , 
6, 2.06226, 1, 0, 0.5,3.20683e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542243,0.00627555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567124,-0.0100362) , 
5, 2.07673, 1, 0, 0.548527,0.0102546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439753,-0.00222481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785139,0.0100903) , 
5, 2.91771, 1, 0, 0.480385,-0.00414014) , 
7, 336.064, 1, 0, 0.5,3.40182e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00600498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614178,0.00538312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509775,-0.000336622) , 
4, -8.95025, 1, 0, 0.523921,0.00188439) , 
3, 2.02257, 1, 0, 0.5,4.79941e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537004,0.000750141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366922,-0.00523422) , 
7, 650.753, 1, 0, 0.505591,-0.00140314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394863,0.00655628) , 
8, 401.726, 1, 0, 0.5,4.05529e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383055,0.00498088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267595,-0.00774816) , 
7, 301.504, 1, 0, 0.307431,-0.0120364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48395,0.00290544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640373,-0.00238033) , 
1, 2.8497, 1, 0, 0.550169,0.00313975) , 
3, 2.90421, 1, 0, 0.5,3.12345e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391568,0.000349862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534401,-0.0120856) , 
5, 2.47884, 1, 0, 0.408619,-0.0048193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655593,0.0128316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654291,-0.00158027) , 
1, 2.75307, 1, 0, 0.654596,0.00815764) , 
3, 4.29627, 1, 0, 0.5,1.66294e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445427,0.000145373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557108,-0.0112282) , 
1, 3.20477, 1, 0, 0.453637,-0.00297003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789468,0.00994271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557672,-0.00502541) , 
7, 479.66, 1, 0, 0.700262,0.0128461) , 
1, 3.37232, 1, 0, 0.5,3.24852e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434793,9.19832e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576358,-0.0106269) , 
3, 4.65178, 1, 0, 0.446555,-0.00337899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579919,-0.00273777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762026,0.00899716) , 
6, 0.0836053, 1, 0, 0.676095,0.0111565) , 
3, 4.9459, 1, 0, 0.5,5.37798e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514926,0.00231372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700446,-0.00820422) , 
5, 2.99594, 1, 0, 0.538752,0.00496578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399001,-0.00310533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713655,0.00729198) , 
5, 2.58182, 1, 0, 0.442834,-0.00730825) , 
2, -0.99005, 1, 0, 0.5,6.87611e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271565,0.00293777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239606,-0.00931662) , 
1, 0.939279, 1, 0, 0.25357,-0.0147714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550223,0.00126717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438377,-0.00596532) , 
4, 0.800993, 1, 0, 0.539555,0.00237915) , 
1, 1.27389, 1, 0, 0.5,7.04635e-06)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415424,-0.00542786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520819,0.00090298) , 
7, 240.216, 1, 0, 0.511999,0.0014597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3045,-0.00607941) , 
7, 951.29, 1, 0, 0.5,5.20708e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468627,-0.00169438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508457,0.00254624) , 
0, 61.6075, 1, 0, 0.487642,0.00136537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.0074439) , 
6, 2.06226, 1, 0, 0.5,4.35504e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483433,-0.000350899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752356,0.00847169) , 
3, 5.88604, 1, 0, 0.50887,0.00155374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00545736) , 
0, 162.275, 1, 0, 0.5,4.30439e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560458,-0.00178627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516894,0.0126223) , 
4, 0.104473, 1, 0, 0.548527,0.00910414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375082,-0.0056834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530974,0.00142334) , 
5, 0.603665, 1, 0, 0.480385,-0.00367347) , 
7, 336.064, 1, 0, 0.5,4.58593e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449313,0.000578742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386134,-0.0134578) , 
6, 0.0115069, 1, 0, 0.439881,-0.00670883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415371,-0.00258456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649995,0.00451933) , 
5, 0.987297, 1, 0, 0.544612,0.00498413) , 
6, 0.0278685, 1, 0, 0.5,3.3149e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494112,0.00912916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499397,-0.00171706) , 
6, 0.363147, 1, 0, 0.496698,0.0160938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540717,0.000884654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420394,-0.00343798) , 
8, 214.643, 1, 0, 0.500472,-0.00229918) , 
5, 0.0340447, 1, 0, 0.5,2.97291e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537004,0.000635576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366922,-0.00467986) , 
7, 650.753, 1, 0, 0.505591,-0.00136096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394863,0.00636276) , 
8, 401.726, 1, 0, 0.5,2.39653e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468627,-0.00153483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508457,0.00235206) , 
0, 61.6075, 1, 0, 0.487642,0.00132248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.00722415) , 
6, 2.06226, 1, 0, 0.5,1.70788e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289649,0.00121375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28695,-0.00710743) , 
5, 0.545624, 1, 0, 0.288132,-0.0136241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647829,0.00690541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521194,-0.000303339) , 
4, -8.95025, 1, 0, 0.536511,0.00235003) , 
3, 2.6258, 1, 0, 0.5,1.90135e-06)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379528,9.12896e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50859,-0.0102598) , 
5, 2.42436, 1, 0, 0.394171,-0.00470922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652841,-0.000659951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609022,0.0164767) , 
8, 303.73, 1, 0, 0.64753,0.00656856) , 
3, 4.11066, 1, 0, 0.5,1.56296e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483934,0.00371893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60148,-0.00209209) , 
5, 1.2937, 1, 0, 0.538752,0.00451632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469713,-0.000386385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260176,-0.0111965) , 
7, 757.933, 1, 0, 0.442834,-0.00665729) , 
2, -0.99005, 1, 0, 0.5,2.00219e-06)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30217,0.00097188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424837,-0.00650737) , 
1, 2.00607, 1, 0, 0.341266,-0.00670311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595646,-0.00648366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605509,0.00225763) , 
7, 285.261, 1, 0, 0.604167,0.00440054) , 
3, 3.46103, 1, 0, 0.5,1.02408e-06)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430835,-0.00788162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588745,0.00570545) , 
0, 32.181, 1, 0, 0.548527,0.00928142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54116,0.00852385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47314,-0.00201055) , 
4, -8.95025, 1, 0, 0.480385,-0.00374995) , 
7, 336.064, 1, 0, 0.5,1.15229e-06)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00527695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554674,0.00142298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432915,-0.00264468) , 
8, 241.369, 1, 0, 0.523921,0.00163679) , 
3, 2.02257, 1, 0, 0.5,1.15911e-06)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443308,-0.00177469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557556,0.00199476) , 
6, 0.0278685, 1, 0, 0.50803,0.00123382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349323,-0.0058404) , 
0, 179.053, 1, 0, 0.5,6.59035e-07)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36739,1.8771e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499933,-0.011754) , 
1, 2.32236, 1, 0, 0.380545,-0.00504914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617241,0.00913147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639023,-0.00163412) , 
1, 2.84585, 1, 0, 0.633255,0.00563344) , 
1, 2.46951, 1, 0, 0.5,4.74908e-07)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560458,-0.00155946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516894,0.0114413) , 
4, 0.104473, 1, 0, 0.548527,0.00842981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439753,-0.00191293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785139,0.00907381) , 
5, 2.91771, 1, 0, 0.480385,-0.00340544) , 
7, 336.064, 1, 0, 0.5,1.36016e-06)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271565,0.00276237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239606,-0.00856092) , 
1, 0.939279, 1, 0, 0.25357,-0.0133018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550223,0.00115294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438377,-0.00547613) , 
4, 0.800993, 1, 0, 0.539555,0.00213737) , 
1, 1.27389, 1, 0, 0.5,1.97437e-06)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456558,0.00112289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634316,-0.00387837) , 
5, 2.36668, 1, 0, 0.487642,0.00123563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.00675278) , 
6, 2.06226, 1, 0, 0.5,8.14605e-07)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426978,0.000855711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547449,-0.0080817) , 
1, 2.85178, 1, 0, 0.446527,-0.00275234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801168,0.010196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598302,-0.00263353) , 
7, 405.56, 1, 0, 0.691799,0.00987806) , 
1, 3.27472, 1, 0, 0.5,1.27493e-06)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396005,0.00389217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284527,-0.00507427) , 
7, 300.909, 1, 0, 0.318525,-0.00841975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587625,0.001739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443548,-0.00694158) , 
4, 0.800991, 1, 0, 0.572544,0.00337048) , 
3, 3.13622, 1, 0, 0.5,3.35017e-06)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511336,0.000307279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379267,-0.00960203) , 
4, 0.703458, 1, 0, 0.502714,-0.00134425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456826,0.00509496) , 
4, 0.900495, 1, 0, 0.5,2.26511e-06)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491247,-0.00751578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507061,0.000198876) , 
8, 113.589, 1, 0, 0.506039,-0.00125683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395306,0.00542146) , 
8, 392.817, 1, 0, 0.5,1.66778e-06)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514926,0.00207663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700446,-0.00770909) , 
5, 2.99594, 1, 0, 0.538752,0.00427243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394853,-0.00301733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637382,0.00507138) , 
6, 0.791295, 1, 0, 0.442834,-0.00629899) , 
2, -0.99005, 1, 0, 0.5,1.40521e-06)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434793,0.000159689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576358,-0.00962577) , 
3, 4.65178, 1, 0, 0.446555,-0.00276713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674382,0.00972577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676904,-0.00143856) , 
3, 5.42147, 1, 0, 0.676095,0.00912532) , 
3, 4.9459, 1, 0, 0.5,1.84859e-06)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391568,0.00031976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534401,-0.0100642) , 
5, 2.47884, 1, 0, 0.408619,-0.00390485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655593,0.0112918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654291,-0.00155125) , 
1, 2.75307, 1, 0, 0.654596,0.00661368) , 
3, 4.29627, 1, 0, 0.5,2.80675e-06)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47984,0.0110754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421945,-0.00274789) , 
4, -8.95025, 1, 0, 0.429596,-0.00371599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623774,-0.00423942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64911,0.00751806) , 
7, 425.325, 1, 0, 0.636483,0.00721494) , 
5, 1.63415, 1, 0, 0.5,3.83181e-06)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00508046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547881,0.0048935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520799,-0.000227535) , 
5, 0.0340447, 1, 0, 0.523921,0.0015734) , 
3, 2.02257, 1, 0, 0.5,3.79816e-06)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36739,-6.33401e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499933,-0.0110504) , 
1, 2.32236, 1, 0, 0.380545,-0.00483554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639677,-0.000370619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583195,0.0134356) , 
8, 303.73, 1, 0, 0.633255,0.00540078) , 
1, 2.46951, 1, 0, 0.5,3.1301e-06)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525607,-0.00184441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549212,0.00389136) , 
8, 150.155, 1, 0, 0.536927,0.00375488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379495,-0.00546916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476206,0.00222218) , 
6, 0.0235296, 1, 0, 0.426314,-0.00748324) , 
8, 214.643, 1, 0, 0.5,3.18933e-06)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446318,-0.00351658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521812,0.000909062) , 
7, 260.767, 1, 0, 0.511999,0.00127305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3045,-0.00537195) , 
7, 951.29, 1, 0, 0.5,2.64069e-06)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506081,-0.00146296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656043,0.0110647) , 
7, 298.285, 1, 0, 0.548527,0.00818785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375082,-0.00515277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530974,0.00129055) , 
5, 0.603665, 1, 0, 0.480385,-0.00330652) , 
7, 336.064, 1, 0, 0.5,2.1574e-06)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483433,-0.000353146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752356,0.00780042) , 
3, 5.88604, 1, 0, 0.50887,0.00129505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00460026) , 
0, 162.275, 1, 0, 0.5,2.22466e-06)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511336,0.000273149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379267,-0.00862228) , 
4, 0.703458, 1, 0, 0.502714,-0.00120609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456826,0.00458033) , 
4, 0.900495, 1, 0, 0.5,2.61799e-06)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483934,0.0033731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60148,-0.00195426) , 
5, 1.2937, 1, 0, 0.538752,0.00396766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521714,0.00468841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423225,-0.00298637) , 
8, 134.465, 1, 0, 0.442834,-0.00584782) , 
2, -0.99005, 1, 0, 0.5,2.05122e-06)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289649,0.00105332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28695,-0.00617389) , 
5, 0.545624, 1, 0, 0.288132,-0.0117018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647829,0.00604033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521194,-0.000272021) , 
4, -8.95025, 1, 0, 0.536511,0.00201856) , 
3, 2.6258, 1, 0, 0.5,1.71699e-06)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22042,-0.00831371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293906,0.00247329) , 
0, 57.9001, 1, 0, 0.25357,-0.0117784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571249,0.00140506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446162,-0.0023232) , 
8, 241.369, 1, 0, 0.539555,0.00189223) , 
1, 1.27389, 1, 0, 0.5,1.44261e-06)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468627,-0.001384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508457,0.00208414) , 
0, 61.6075, 1, 0, 0.487642,0.00111392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.00607611) , 
6, 2.06226, 1, 0, 0.5,4.42991e-07)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493153,-0.000660253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604347,0.012348) , 
0, 72.2919, 1, 0, 0.50555,0.00320543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538263,-0.00630824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428277,0.00360864) , 
7, 517.637, 1, 0, 0.487598,-0.00716155) , 
0, 83.9781, 1, 0, 0.5,6.49106e-07)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407446,-0.0056608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533644,0.00103751) , 
7, 238.38, 1, 0, 0.522698,0.00178496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3252,-0.00738903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347,0.00212449) , 
0, 95.1634, 1, 0, 0.334638,-0.0129945) , 
7, 775.511, 1, 0, 0.5,1.14836e-06)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560458,-0.00148355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516894,0.0108188) , 
4, 0.104473, 1, 0, 0.548527,0.00788526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425651,-0.00209707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735645,0.00625296) , 
5, 2.51527, 1, 0, 0.480385,-0.00318644) , 
7, 336.064, 1, 0, 0.5,5.6826e-07)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492366,-0.000172168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772176,0.00943731) , 
3, 6.30107, 1, 0, 0.50887,0.00124774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375009,-0.00443923) , 
0, 162.275, 1, 0, 0.5,8.56351e-07)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537004,0.000566494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366922,-0.00401092) , 
7, 650.753, 1, 0, 0.505591,-0.00107438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394863,0.00505455) , 
8, 401.726, 1, 0, 0.5,1.35674e-06)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456558,0.00102521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634316,-0.00364596) , 
5, 2.36668, 1, 0, 0.487642,0.00105103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.00572675) , 
6, 2.06226, 1, 0, 0.5,9.16648e-07)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47984,0.0102337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421945,-0.00256031) , 
4, -8.95025, 1, 0, 0.429596,-0.00348653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59769,-0.00894491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646875,0.00453373) , 
4, -8.95025, 1, 0, 0.636483,0.00676252) , 
5, 1.63415, 1, 0, 0.5,1.24199e-06)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00449624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547881,0.00454106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520799,-0.000231917) , 
5, 0.0340447, 1, 0, 0.523921,0.00137924) , 
3, 2.02257, 1, 0, 0.5,1.46613e-06)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476056,0.00882037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421112,-0.00228533) , 
4, -8.95025, 1, 0, 0.428371,-0.00327422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528149,-0.0073182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660601,0.00386923) , 
7, 302.769, 1, 0, 0.633802,0.00611934) , 
5, 1.6001, 1, 0, 0.5,1.09995e-06)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560458,-0.00131474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516894,0.0100095) , 
4, 0.104473, 1, 0, 0.548527,0.00745993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375082,-0.00454818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530974,0.00109913) , 
5, 0.603665, 1, 0, 0.480385,-0.0030138) , 
7, 336.064, 1, 0, 0.5,1.0774e-06)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396005,0.00399648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284527,-0.00468248) , 
7, 300.909, 1, 0, 0.318525,-0.00715721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515034,0.00284674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641768,-0.00211829) , 
1, 2.8651, 1, 0, 0.572544,0.00286179) , 
3, 3.13622, 1, 0, 0.5,5.00849e-07)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36739,3.16053e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499933,-0.0104086) , 
1, 2.32236, 1, 0, 0.380545,-0.00440382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639677,-0.000392346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583195,0.012677) , 
8, 303.73, 1, 0, 0.633255,0.0049124) , 
1, 2.46951, 1, 0, 0.5,-7.82563e-08)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483934,0.00332132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60148,-0.00203237) , 
5, 1.2937, 1, 0, 0.538752,0.00369579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425492,-0.00374388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465931,0.00187536) , 
0, 65.3505, 1, 0, 0.442834,-0.00545118) , 
2, -0.99005, 1, 0, 0.5,2.67896e-07)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435794,-0.00468401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543949,0.00166991) , 
7, 259.33, 1, 0, 0.527247,0.00261504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415041,-0.00797726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419969,0.00254093) , 
8, 290.035, 1, 0, 0.417894,-0.00787973) , 
8, 241.369, 1, 0, 0.5,1.03379e-07)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493153,-0.000513742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604347,0.0109934) , 
0, 72.2919, 1, 0, 0.50555,0.00310273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538263,-0.00593509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428277,0.003295) , 
7, 517.637, 1, 0, 0.487598,-0.00693485) , 
0, 83.9781, 1, 0, 0.5,-2.18962e-07)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556908,0.00234545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537802,-0.00844986) , 
0, 106.255, 1, 0, 0.554517,0.00412082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308333,-0.00640504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530853,0.00290928) , 
5, 0.978391, 1, 0, 0.425381,-0.00563955) , 
7, 476.687, 1, 0, 0.5,2.95343e-07)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494112,0.00770151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499397,-0.00225107) , 
6, 0.363147, 1, 0, 0.496698,0.0118639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449237,-0.00135424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696171,0.00376825) , 
6, 0.891787, 1, 0, 0.500472,-0.00169771) , 
5, 0.0340447, 1, 0, 0.5,-2.81588e-07)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523024,-0.000153206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401434,0.00457882) , 
7, 725.221, 1, 0, 0.511999,0.00110964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3045,-0.00473823) , 
7, 951.29, 1, 0, 0.5,-9.1636e-08)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430835,-0.00684672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588745,0.0046547) , 
0, 32.181, 1, 0, 0.548527,0.00707695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528956,0.0019159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432952,-0.00327085) , 
4, 0.104476, 1, 0, 0.480385,-0.00286101) , 
7, 336.064, 1, 0, 0.5,-3.50771e-07)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511336,0.000216503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379267,-0.00755723) , 
4, 0.703458, 1, 0, 0.502714,-0.00113032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456826,0.0043009) , 
4, 0.900495, 1, 0, 0.5,-3.45656e-07)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228017,-0.00433069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518428,0.003774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524895,-0.00030594) , 
5, 0.136179, 1, 0, 0.523921,0.00132103) , 
3, 2.02257, 1, 0, 0.5,-5.56382e-07)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456558,0.00103542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634316,-0.00372684) , 
5, 2.36668, 1, 0, 0.487642,0.00102757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727097,-0.00562289) , 
6, 2.06226, 1, 0, 0.5,-7.35155e-07)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30217,0.00115432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424837,-0.00582332) , 
1, 2.00607, 1, 0, 0.341266,-0.00520871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428787,-0.00564052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62861,0.00179252) , 
1, 1.94141, 1, 0, 0.604167,0.00341776) , 
3, 3.46103, 1, 0, 0.5,-2.45364e-07)    );
   return;
};

// Clean up
inline void ReadtZq::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadtZq::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
