// Class: Readall_SR__tZq
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::all_SR__tZq
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : ntonon
Date           : Mon Jan 13 23:32:30 2020
Host           : Linux cmspcx36679 4.15.0-1065-oem #75-Ubuntu SMP Wed Nov 20 10:51:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ntonon/Postdoc/EFTSimulations/myAnalysis
Training events: 75868
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
DoBoostMonitor: "True" [Create control plot with ROC integral vs tree number]
nEventsMin: "100" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "0.1318083.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "1" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 1
metEt                         metEt                         metEt                         metEt                                                           'F'    [0,940.886535645]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new all_SR__tZqNode

#ifndef all_SR__tZqNode__def
#define all_SR__tZqNode__def

class all_SR__tZqNode {

public:

   // constructor of an essentially "empty" node floating in space
   all_SR__tZqNode ( all_SR__tZqNode* left,all_SR__tZqNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~all_SR__tZqNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   all_SR__tZqNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   all_SR__tZqNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   all_SR__tZqNode*   fLeft;     // pointer to the left daughter node
   all_SR__tZqNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   all_SR__tZqNode::~all_SR__tZqNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool all_SR__tZqNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool all_SR__tZqNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Readall_SR__tZq : public IClassifierReader {

 public:

   // constructor
   Readall_SR__tZq( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "Readall_SR__tZq" ),
        fNvars( 1 )
   {
      // the training input variables
      const char* inputVars[] = { "metEt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;

      // initialize input variable types
      fType[0] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Readall_SR__tZq() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[1];
   double fVmax[1];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[1];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<all_SR__tZqNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Readall_SR__tZq::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      all_SR__tZqNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(all_SR__tZqNode*)current->GetRight();
         else current=(all_SR__tZqNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void Readall_SR__tZq::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679799,0.0359599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565976,0.0131952) , 
0, 4.5164, 1, 0, 0.675438,0.175438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481895,-0.00362103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308947,-0.0382107) , 
0, 125.23, 1, 0, 0.454164,-0.0458357) , 
0, 9.36205, 1, 0, 0.507987,0.00798696)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679799,0.0324073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565976,0.0118779) , 
0, 4.5164, 1, 0, 0.675438,0.157901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481895,-0.00325897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308947,-0.0344417) , 
0, 125.23, 1, 0, 0.454164,-0.0412536) , 
0, 9.36205, 1, 0, 0.507987,0.00718895)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679799,0.0292702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565976,0.0106952) , 
0, 4.5164, 1, 0, 0.675438,0.142135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48821,-0.00167005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341559,-0.0265633) , 
0, 106.692, 1, 0, 0.454164,-0.037133) , 
0, 9.36205, 1, 0, 0.507987,0.00647222)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.026081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420831,-0.019434) , 
0, 8.70687, 1, 0, 0.675438,0.127953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470628,-0.00398312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246284,-0.0412576) , 
0, 166.939, 1, 0, 0.454164,-0.0334247) , 
0, 9.36205, 1, 0, 0.507987,0.00582901)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679799,0.0240146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565976,0.00769968) , 
0, 4.5164, 1, 0, 0.675438,0.115193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48821,-0.00110488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341559,-0.0225054) , 
0, 106.692, 1, 0, 0.454164,-0.0300893) , 
0, 9.36205, 1, 0, 0.507987,0.0052492)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.0214074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420831,-0.0182473) , 
0, 8.70687, 1, 0, 0.675438,0.103709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470628,-0.00311295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246284,-0.0355151) , 
0, 166.939, 1, 0, 0.454164,-0.0270863) , 
0, 9.36205, 1, 0, 0.507987,0.00472852)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679799,0.01976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565976,0.00538869) , 
0, 4.5164, 1, 0, 0.675438,0.093372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48821,-0.000683204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341559,-0.0191219) , 
0, 106.692, 1, 0, 0.454164,-0.0243855) , 
0, 9.36205, 1, 0, 0.507987,0.00425789)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679719,0.017899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517756,0.00467489) , 
0, 4.47119, 1, 0, 0.61558,0.0614199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463591,-0.00380538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273784,-0.0266918) , 
0, 149.819, 1, 0, 0.440006,-0.0325479) , 
0, 37.4482, 1, 0, 0.507987,0.00383556)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679719,0.0162283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517756,0.00420703) , 
0, 4.47119, 1, 0, 0.61558,0.0552958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450055,-0.00456527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177764,-0.0429564) , 
0, 217.24, 1, 0, 0.440006,-0.029302) , 
0, 37.4482, 1, 0, 0.507987,0.00345349)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679719,0.0147117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517756,0.00378618) , 
0, 4.47119, 1, 0, 0.61558,0.0497821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463591,-0.00297051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273784,-0.0229129) , 
0, 149.819, 1, 0, 0.440006,-0.0263804) , 
0, 37.4482, 1, 0, 0.507987,0.00310902)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676877,0.0131584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513412,0.00313467) , 
0, 8.75608, 1, 0, 0.61558,0.0448178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450055,-0.00364578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177764,-0.0378033) , 
0, 217.24, 1, 0, 0.440006,-0.02375) , 
0, 37.4482, 1, 0, 0.507987,0.00279884)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.011906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489058,0.000257409) , 
0, 8.7095, 1, 0, 0.545203,0.0176509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372997,-0.0101143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173702,-0.0358101) , 
0, 219.711, 1, 0, 0.350249,-0.0616187) , 
0, 102.983, 1, 0, 0.507987,0.00251877)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679787,0.0109912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505073,0.00220923) , 
0, 3.63295, 1, 0, 0.581619,0.0286877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436627,-0.00446534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172402,-0.033408) , 
0, 219.043, 1, 0, 0.424228,-0.0277911) , 
0, 56.1723, 1, 0, 0.507987,0.00226527)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679649,0.00992501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489356,0.000277331) , 
0, 4.2815, 1, 0, 0.543122,0.0140144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363385,-0.00930935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173702,-0.0305607) , 
0, 219.615, 1, 0, 0.339423,-0.0554211) , 
0, 107.664, 1, 0, 0.507987,0.00203785)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.00886356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489058,0.000308798) , 
0, 8.7095, 1, 0, 0.545203,0.0133447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372997,-0.00790053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173702,-0.0282363) , 
0, 219.711, 1, 0, 0.350249,-0.0469627) , 
0, 102.983, 1, 0, 0.507987,0.00183234)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679787,0.00816732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505073,0.00190335) , 
0, 3.63295, 1, 0, 0.581619,0.0217843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447138,-0.00285374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242342,-0.0180061) , 
0, 170.626, 1, 0, 0.424228,-0.0212585) , 
0, 56.1723, 1, 0, 0.507987,0.00164757)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613346,0.00552972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477485,-0.000842131) , 
0, 39.0687, 1, 0, 0.543122,0.010512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363385,-0.0070888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173702,-0.0246852) , 
0, 219.615, 1, 0, 0.339423,-0.0418401) , 
0, 107.664, 1, 0, 0.507987,0.0014821)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.00672984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489058,0.000226447) , 
0, 8.7095, 1, 0, 0.545203,0.00998719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372997,-0.00598459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173702,-0.0227636) , 
0, 219.711, 1, 0, 0.350249,-0.0353544) , 
0, 102.983, 1, 0, 0.507987,0.00133171)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556991,0.00206545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622068,0.0284071) , 
0, 77.9876, 1, 0, 0.558035,0.012105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42843,-0.00319877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243215,-0.0140374) , 
0, 169.585, 1, 0, 0.396907,-0.0230122) , 
0, 79.5775, 1, 0, 0.507987,0.00119735)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679787,0.00601197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505073,0.00119476) , 
0, 3.63295, 1, 0, 0.581619,0.0152967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441129,-0.00226705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213345,-0.0161927) , 
0, 192.634, 1, 0, 0.424228,-0.015101) , 
0, 56.1723, 1, 0, 0.507987,0.00107576)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588864,0.00341865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472313,-0.00136845) , 
0, 52.4484, 1, 0, 0.543122,0.00723278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343115,-0.00589073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0605124,-0.0494294) , 
0, 356.408, 1, 0, 0.339423,-0.0290901) , 
0, 107.664, 1, 0, 0.507987,0.000967654)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613346,0.0036756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477485,-0.00071797) , 
0, 39.0687, 1, 0, 0.543122,0.00650996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343115,-0.00531836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0605124,-0.0470337) , 
0, 356.408, 1, 0, 0.339423,-0.0261912) , 
0, 107.664, 1, 0, 0.507987,0.000869534)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.00456469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.0141106) , 
0, 2.16203, 1, 0, 0.679335,0.0210149) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481097,-0.00019038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300517,-0.00742322) , 
0, 130.456, 1, 0, 0.455586,-0.00540622) , 
0, 4.68103, 1, 0, 0.507987,0.000781518)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588864,0.00261872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472313,-0.00114102) , 
0, 52.4484, 1, 0, 0.543122,0.00533383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343782,-0.00430943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0792285,-0.0397305) , 
0, 339.827, 1, 0, 0.339423,-0.0215124) , 
0, 107.664, 1, 0, 0.507987,0.000703281)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.00407709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00479629) , 
0, 0.0230003, 1, 0, 0.679335,0.0177431) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00906179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-0.000497209) , 
0, 18.6727, 1, 0, 0.455586,-0.00460096) , 
0, 4.68103, 1, 0, 0.507987,0.000631942)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523162,0.000485306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522206,0.0392733) , 
0, 165.159, 1, 0, 0.523159,0.00279029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233403,-0.0201779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245377,-0.00693757) , 
0, 180.075, 1, 0, 0.24322,-0.0381865) , 
0, 168.517, 1, 0, 0.507987,0.000569391)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544682,0.00052685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510832,0.00877555) , 
0, 97.9394, 1, 0, 0.543122,0.00444321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363385,-0.00287353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173702,-0.015026) , 
0, 219.615, 1, 0, 0.339423,-0.0183546) , 
0, 107.664, 1, 0, 0.507987,0.000510947)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620433,0.000774403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578546,0.0134785) , 
0, 30.9257, 1, 0, 0.61558,0.0109735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441369,-0.00117842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0491222,-0.0452179) , 
0, 361.07, 1, 0, 0.440006,-0.00618492) , 
0, 37.4482, 1, 0, 0.507987,0.000458687)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.0032946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.0128494) , 
0, 2.16203, 1, 0, 0.679335,0.0151738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.0083282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-0.000429984) , 
0, 18.6727, 1, 0, 0.455586,-0.00410231) , 
0, 4.68103, 1, 0, 0.507987,0.000412084)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556991,0.00072324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622068,0.0262102) , 
0, 77.9876, 1, 0, 0.558035,0.00552032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00713622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,-0.00138389) , 
0, 88.1696, 1, 0, 0.396907,-0.0110567) , 
0, 79.5775, 1, 0, 0.507987,0.000371355)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523162,0.000343265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522206,0.0351998) , 
0, 165.159, 1, 0, 0.523159,0.00206474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233403,-0.0179391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245377,-0.00508102) , 
0, 180.075, 1, 0, 0.24322,-0.0298667) , 
0, 168.517, 1, 0, 0.507987,0.000334091)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.00302591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420831,-0.019531) , 
0, 8.70687, 1, 0, 0.675438,0.0128856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417814,-0.0171707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454837,-0.000456723) , 
0, 14.0038, 1, 0, 0.454164,-0.00374585) , 
0, 9.36205, 1, 0, 0.507987,0.000299593)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544571,0.000348118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576866,0.0196804) , 
0, 98.8784, 1, 0, 0.545203,0.0035702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353608,-0.00274907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0427761) , 
0, 361.445, 1, 0, 0.350249,-0.013718) , 
0, 102.983, 1, 0, 0.507987,0.000269964)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581513,0.00123049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601917,0.0232387) , 
0, 55.8915, 1, 0, 0.581619,0.00641406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436627,-0.00102713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172402,-0.0127098) , 
0, 219.043, 1, 0, 0.424228,-0.00677897) , 
0, 56.1723, 1, 0, 0.507987,0.000241974)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.00217173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0128729) , 
0, 6.51852, 1, 0, 0.675438,0.0108954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417814,-0.0156117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454837,-0.000375777) , 
0, 14.0038, 1, 0, 0.454164,-0.00321515) , 
0, 9.36205, 1, 0, 0.507987,0.000217114)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588543,0.00156093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44249,-0.00108892) , 
0, 52.5124, 1, 0, 0.51866,0.0012994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223079,-0.0127202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204641,-0.000866913) , 
0, 244.242, 1, 0, 0.21527,-0.030078) , 
0, 191.922, 1, 0, 0.507987,0.000195603)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613254,0.00171415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450901,-0.000753043) , 
0, 39.1155, 1, 0, 0.518028,0.00113218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214096,-0.0133125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204409,-0.000927015) , 
0, 241.075, 1, 0, 0.209453,-0.0282671) , 
0, 196.603, 1, 0, 0.507987,0.000175528)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58843,0.00126841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437956,-0.000929321) , 
0, 52.5352, 1, 0, 0.515361,0.00088429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979961,-0.033455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204845,-0.0006987) , 
0, 241.55, 1, 0, 0.1748,-0.0326797) , 
0, 220.008, 1, 0, 0.507987,0.000157533)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509525,2.34309e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314004,0.0298329) , 
0, 313.147, 1, 0, 0.509025,0.000367908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0591106,-0.0370608) , 
0, 355.758, 1, 0, 0.507987,0.000140504)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.00196356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00696831) , 
0, 0.0230003, 1, 0, 0.679335,0.00815774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00722037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-0.000108453) , 
0, 18.6727, 1, 0, 0.455586,-0.00233097) , 
0, 4.68103, 1, 0, 0.507987,0.000125447)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58843,0.00112421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437956,-0.000828084) , 
0, 52.5352, 1, 0, 0.515361,0.000771253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979961,-0.0313933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204845,-0.000697709) , 
0, 241.55, 1, 0, 0.1748,-0.0296249) , 
0, 220.008, 1, 0, 0.507987,0.000113089)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613622,0.00127021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439468,-0.000705445) , 
0, 38.9222, 1, 0, 0.509025,0.000305368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0591106,-0.0351737) , 
0, 355.758, 1, 0, 0.507987,0.000100661)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528736,-7.69121e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386969,0.00608818) , 
0, 139.581, 1, 0, 0.522014,0.000972636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173821,-0.0297316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24621,-0.000823748) , 
0, 180.918, 1, 0, 0.237945,-0.0168995) , 
0, 173.198, 1, 0, 0.507987,9.01387e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544704,-1.57365e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564648,0.0162788) , 
0, 97.8538, 1, 0, 0.545203,0.00195758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390574,-0.0039738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307974,0.000954361) , 
0, 140.506, 1, 0, 0.350249,-0.00787781) , 
0, 102.983, 1, 0, 0.507987,8.00595e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,3.46535e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.0323646) , 
0, 146.012, 1, 0, 0.527274,0.00120238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0188063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.00207338) , 
0, 153.74, 1, 0, 0.274076,-0.0136391) , 
0, 149.793, 1, 0, 0.507987,7.1825e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509525,2.90701e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314004,0.02636) , 
0, 313.147, 1, 0, 0.509025,0.000247227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0591106,-0.0332743) , 
0, 355.758, 1, 0, 0.507987,6.36236e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533885,0.000356775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315353,-0.0130793) , 
0, 128.446, 1, 0, 0.532659,0.00136608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263857,-0.023518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30788,0.000540677) , 
0, 139.135, 1, 0, 0.302755,-0.0108374) , 
0, 131.069, 1, 0, 0.507987,5.64919e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58843,0.00089905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437956,-0.000663446) , 
0, 52.5352, 1, 0, 0.515361,0.000613353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979961,-0.0292945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204845,-0.000150292) , 
0, 241.55, 1, 0, 0.1748,-0.0254088) , 
0, 220.008, 1, 0, 0.507987,4.98994e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509474,-4.82884e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362781,0.0357452) , 
0, 314.497, 1, 0, 0.509185,0.000229747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0805485,-0.0267102) , 
0, 341.715, 1, 0, 0.507987,4.39427e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528243,-0.000104457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349468,0.00320217) , 
0, 141.188, 1, 0, 0.515361,0.000554349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979961,-0.027419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204845,-0.000283491) , 
0, 241.55, 1, 0, 0.1748,-0.0232589) , 
0, 220.008, 1, 0, 0.507987,3.87246e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528307,-9.87927e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470498,0.0177319) , 
0, 140.797, 1, 0, 0.527274,0.00103433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0173977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.00179972) , 
0, 153.74, 1, 0, 0.274076,-0.012099) , 
0, 149.793, 1, 0, 0.507987,3.38913e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000126013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447075,0.00268164) , 
0, 94.5415, 1, 0, 0.532659,0.00123404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263857,-0.0213672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30788,0.000412631) , 
0, 139.135, 1, 0, 0.302755,-0.00998859) , 
0, 131.069, 1, 0, 0.507987,2.9702e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512614,-7.52625e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269083,0.0162277) , 
0, 242.865, 1, 0, 0.510957,0.00033608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0749874,-0.0414195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187309,-0.00176783) , 
0, 296.237, 1, 0, 0.161587,-0.0361427) , 
0, 276.181, 1, 0, 0.507987,2.59361e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556991,7.13539e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622068,0.0242072) , 
0, 77.9876, 1, 0, 0.558035,0.0022765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00580614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,-0.00010661) , 
0, 88.1696, 1, 0, 0.396907,-0.00498069) , 
0, 79.5775, 1, 0, 0.507987,2.23563e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.0012289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.0108494) , 
0, 2.16203, 1, 0, 0.679335,0.0058786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00682911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-8.6331e-06) , 
0, 18.6727, 1, 0, 0.455586,-0.00177154) , 
0, 4.68103, 1, 0, 0.507987,2.00951e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520045,1.59473e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368036,0.0142289) , 
0, 180.452, 1, 0, 0.51866,0.000628051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223079,-0.00769687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204641,-0.00020217) , 
0, 244.242, 1, 0, 0.21527,-0.0167077) , 
0, 191.922, 1, 0, 0.507987,1.82137e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,1.34411e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.0263355) , 
0, 146.012, 1, 0, 0.527274,0.000927475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0158609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.00165983) , 
0, 153.74, 1, 0, 0.274076,-0.0110395) , 
0, 149.793, 1, 0, 0.507987,1.58887e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509489,-9.84215e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373955,0.0346278) , 
0, 313.411, 1, 0, 0.509243,0.00018538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0972919,-0.0250885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772229,-0.0207737) , 
0, 383.058, 1, 0, 0.0881817,-0.0573488) , 
0, 337.034, 1, 0, 0.507987,1.36896e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533885,0.000293981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315353,-0.0120139) , 
0, 128.446, 1, 0, 0.532659,0.00109433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263857,-0.0194696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30788,0.000370727) , 
0, 139.135, 1, 0, 0.302755,-0.00899468) , 
0, 131.069, 1, 0, 0.507987,1.16494e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512614,-9.91008e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269083,0.0145564) , 
0, 242.865, 1, 0, 0.510957,0.000291922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690378,-0.0409999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186057,-0.00224493) , 
0, 292.931, 1, 0, 0.161587,-0.0328969) , 
0, 276.181, 1, 0, 0.507987,9.74936e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589049,0.000885477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436885,-0.00071286) , 
0, 52.4, 1, 0, 0.514848,0.00044899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0734225,-0.0342631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209133,0.00101063) , 
0, 242.941, 1, 0, 0.175693,-0.0213541) , 
0, 224.689, 1, 0, 0.507987,7.91619e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-1.35381e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0373239) , 
0, 312.292, 1, 0, 0.509429,0.000185805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.0072458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0325599) , 
0, 361.707, 1, 0, 0.111117,-0.0494612) , 
0, 327.672, 1, 0, 0.507987,6.05681e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512614,-8.12097e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269083,0.0127633) , 
0, 242.865, 1, 0, 0.510957,0.000263861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0749874,-0.0371952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187309,-0.00175608) , 
0, 296.237, 1, 0, 0.161587,-0.0302134) , 
0, 276.181, 1, 0, 0.507987,4.74234e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515894,3.01175e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298482,0.0151847) , 
0, 211.83, 1, 0, 0.514848,0.000408643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0734225,-0.0323622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209133,0.000768079) , 
0, 242.941, 1, 0, 0.175693,-0.0196164) , 
0, 224.689, 1, 0, 0.507987,3.53968e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528736,-7.55255e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386969,0.00441192) , 
0, 139.581, 1, 0, 0.522014,0.000620815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173821,-0.0273938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24621,0.000264956) , 
0, 180.918, 1, 0, 0.237945,-0.0119105) , 
0, 173.198, 1, 0, 0.507987,2.03958e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000172398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447075,0.00252039) , 
0, 94.5415, 1, 0, 0.532659,0.000935973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263857,-0.0176732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30788,0.000412187) , 
0, 139.135, 1, 0, 0.302755,-0.00777674) , 
0, 131.069, 1, 0, 0.507987,9.85356e-07)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,4.7694e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.022986) , 
0, 146.012, 1, 0, 0.527274,0.000784419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0148336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.00134668) , 
0, 153.74, 1, 0, 0.274076,-0.00950959) , 
0, 149.793, 1, 0, 0.507987,2.72851e-07)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557263,-7.54802e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513013,0.00686615) , 
0, 77.1309, 1, 0, 0.554604,0.00171685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416685,-0.00984795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388186,-4.68061e-05) , 
0, 88.5237, 1, 0, 0.390586,-0.00432443) , 
0, 84.2585, 1, 0, 0.507987,-1.89534e-07)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.000798708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0121371) , 
0, 6.51852, 1, 0, 0.675438,0.00482169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417814,-0.0135351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454837,-6.75251e-05) , 
0, 14.0038, 1, 0, 0.454164,-0.0015502) , 
0, 9.36205, 1, 0, 0.507987,-2.96157e-07)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-2.81293e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0325766) , 
0, 312.292, 1, 0, 0.509429,0.000160245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.00641156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0308096) , 
0, 361.707, 1, 0, 0.111117,-0.0441629) , 
0, 327.672, 1, 0, 0.507987,-2.27584e-07)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544571,-6.4734e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576866,0.0162368) , 
0, 98.8784, 1, 0, 0.545203,0.00128329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.0062456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,-0.000270387) , 
0, 111.326, 1, 0, 0.350249,-0.00544325) , 
0, 102.983, 1, 0, 0.507987,-7.74358e-07)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556991,1.5177e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622068,0.0212007) , 
0, 77.9876, 1, 0, 0.558035,0.0017691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00506864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,1.37157e-05) , 
0, 88.1696, 1, 0, 0.396907,-0.003929) , 
0, 79.5775, 1, 0, 0.507987,-7.7657e-07)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000151692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439696,0.00213885) , 
0, 94.5466, 1, 0, 0.530763,0.000858529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0604033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000850471) , 
0, 139.763, 1, 0, 0.299406,-0.00786897) , 
0, 135.75, 1, 0, 0.507987,-6.42147e-07)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620433,-0.000785337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578546,0.0111722) , 
0, 30.9257, 1, 0, 0.61558,0.00328009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479721,-0.00283512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435091,-0.000120823) , 
0, 46.4412, 1, 0, 0.440006,-0.00207711) , 
0, 37.4482, 1, 0, 0.507987,-2.85236e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.0012498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00765757) , 
0, 0.0230003, 1, 0, 0.679335,0.00498347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00583863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-1.02851e-05) , 
0, 18.6727, 1, 0, 0.455586,-0.00152718) , 
0, 4.68103, 1, 0, 0.507987,-2.41247e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520045,-4.40721e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368036,0.0129929) , 
0, 180.452, 1, 0, 0.51866,0.000487537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223079,-0.00604472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204641,-0.000589973) , 
0, 244.242, 1, 0, 0.21527,-0.0134307) , 
0, 191.922, 1, 0, 0.507987,-2.07831e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611732,0.000916557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441325,-0.00052534) , 
0, 39.7915, 1, 0, 0.510957,0.000232965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690378,-0.0370247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186057,-0.00205261) , 
0, 292.931, 1, 0, 0.161587,-0.0274309) , 
0, 276.181, 1, 0, 0.507987,-2.23395e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528307,-9.94427e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470498,0.0133446) , 
0, 140.797, 1, 0, 0.527274,0.000678437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0134713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.00113464) , 
0, 153.74, 1, 0, 0.274076,-0.00826001) , 
0, 149.793, 1, 0, 0.507987,-2.44913e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-3.93495e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0288338) , 
0, 312.292, 1, 0, 0.509429,0.00013912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.00550324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0290034) , 
0, 361.707, 1, 0, 0.111117,-0.0390102) , 
0, 327.672, 1, 0, 0.507987,-2.62085e-06)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000149679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439696,0.0020006) , 
0, 94.5466, 1, 0, 0.530763,0.00077165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0567698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000765267) , 
0, 139.763, 1, 0, 0.299406,-0.00709547) , 
0, 135.75, 1, 0, 0.507987,-2.82171e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557263,-6.27558e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513013,0.00606687) , 
0, 77.1309, 1, 0, 0.554604,0.00153407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416685,-0.00828532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388186,-9.89217e-05) , 
0, 88.5237, 1, 0, 0.390586,-0.00388016) , 
0, 84.2585, 1, 0, 0.507987,-4.74923e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544571,-5.26982e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576866,0.0142846) , 
0, 98.8784, 1, 0, 0.545203,0.00114909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.00595431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,-0.000180021) , 
0, 111.326, 1, 0, 0.350249,-0.00489329) , 
0, 102.983, 1, 0, 0.507987,-4.37225e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556991,2.40038e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622068,0.0186327) , 
0, 77.9876, 1, 0, 0.558035,0.00160144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00440033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,-2.94755e-05) , 
0, 88.1696, 1, 0, 0.396907,-0.00356717) , 
0, 79.5775, 1, 0, 0.507987,-3.97163e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.000659213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0115685) , 
0, 6.51852, 1, 0, 0.675438,0.00415237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417814,-0.0115748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454837,-6.09915e-05) , 
0, 14.0038, 1, 0, 0.454164,-0.00133928) , 
0, 9.36205, 1, 0, 0.507987,-3.48837e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512614,-1.40956e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269083,0.0115088) , 
0, 242.865, 1, 0, 0.510957,0.000209217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690378,-0.0350364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186057,-0.00188826) , 
0, 292.931, 1, 0, 0.161587,-0.0247657) , 
0, 276.181, 1, 0, 0.507987,-3.12026e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515894,1.63055e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298482,0.0143216) , 
0, 211.83, 1, 0, 0.514848,0.00032954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0734225,-0.0300811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209133,0.00114982) , 
0, 242.941, 1, 0, 0.175693,-0.0161274) , 
0, 224.689, 1, 0, 0.507987,-3.38139e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523162,3.43307e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522206,0.0312849) , 
0, 165.159, 1, 0, 0.523159,0.000536892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233403,-0.0132793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245377,0.000117398) , 
0, 180.075, 1, 0, 0.24322,-0.00944316) , 
0, 168.517, 1, 0, 0.507987,-4.01585e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581513,0.000314888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601917,0.0216418) , 
0, 55.8915, 1, 0, 0.581619,0.00204044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454948,-0.00385439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421999,-0.000232616) , 
0, 60.5893, 1, 0, 0.424228,-0.00233) , 
0, 56.1723, 1, 0, 0.507987,-4.18127e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512671,-7.55338e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291388,0.016946) , 
0, 242.445, 1, 0, 0.51172,0.000222891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163147,-0.0128572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191299,0.00241514) , 
0, 312.907, 1, 0, 0.175571,-0.0201863) , 
0, 262.138, 1, 0, 0.507987,-3.77802e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519961,-1.8762e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352995,0.00968383) , 
0, 180.909, 1, 0, 0.518028,0.000391674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185005,-0.0244585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21127,-0.00157998) , 
0, 200.345, 1, 0, 0.209453,-0.0117626) , 
0, 196.603, 1, 0, 0.507987,-3.82655e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,-5.84362e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.0191348) , 
0, 146.012, 1, 0, 0.527274,0.000612734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0122577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.00103523) , 
0, 153.74, 1, 0, 0.274076,-0.0074818) , 
0, 149.793, 1, 0, 0.507987,-3.86653e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543405,5.88705e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514855,0.0141614) , 
0, 105.432, 1, 0, 0.543122,0.000972651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364992,-0.00874639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337669,-0.000484513) , 
0, 111.839, 1, 0, 0.339423,-0.00468815) , 
0, 107.664, 1, 0, 0.507987,-3.74837e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-4.13595e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0255161) , 
0, 312.292, 1, 0, 0.509429,0.000123283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.00487733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0273459) , 
0, 361.707, 1, 0, 0.111117,-0.0349065) , 
0, 327.672, 1, 0, 0.507987,-3.54339e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.000755831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.0103382) , 
0, 2.16203, 1, 0, 0.679335,0.00378335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495302,-0.00336398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450403,0.000180623) , 
0, 27.988, 1, 0, 0.455586,-0.00116167) , 
0, 4.68103, 1, 0, 0.507987,-3.56701e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651748,-0.00077368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572347,0.0122773) , 
0, 17.204, 1, 0, 0.643597,0.00320665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455091,-0.0119578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45043,0.000169805) , 
0, 28.0115, 1, 0, 0.450598,-0.0013615) , 
0, 23.4051, 1, 0, 0.507987,-3.13722e-06)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620433,-0.000744076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578546,0.00994644) , 
0, 30.9257, 1, 0, 0.61558,0.00273414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475531,-0.00377213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438085,-0.000167578) , 
0, 41.9464, 1, 0, 0.440006,-0.00173192) , 
0, 37.4482, 1, 0, 0.507987,-2.69946e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.0010426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00780798) , 
0, 0.0230003, 1, 0, 0.679335,0.00407054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00484065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-4.72955e-06) , 
0, 18.6727, 1, 0, 0.455586,-0.00124782) , 
0, 4.68103, 1, 0, 0.507987,-2.27656e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651748,-0.000635865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572347,0.011234) , 
0, 17.204, 1, 0, 0.643597,0.00321742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455091,-0.0106804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45043,0.00012009) , 
0, 28.0115, 1, 0, 0.450598,-0.0013644) , 
0, 23.4051, 1, 0, 0.507987,-1.97515e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.000608122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0114152) , 
0, 6.51852, 1, 0, 0.675438,0.00391393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417814,-0.00944576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454837,-8.54035e-05) , 
0, 14.0038, 1, 0, 0.454164,-0.00126025) , 
0, 9.36205, 1, 0, 0.507987,-1.68031e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55728,-5.30598e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589058,0.0139353) , 
0, 77.1958, 1, 0, 0.558035,0.00140037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00396105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,-1.73281e-06) , 
0, 88.1696, 1, 0, 0.396907,-0.0031129) , 
0, 79.5775, 1, 0, 0.507987,-1.48566e-06)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581513,0.000306476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601917,0.0194577) , 
0, 55.8915, 1, 0, 0.581619,0.0019438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454948,-0.00348862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421999,-0.000234473) , 
0, 60.5893, 1, 0, 0.424228,-0.00221391) , 
0, 56.1723, 1, 0, 0.507987,-1.30061e-06)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58843,0.000674976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437956,-0.000565464) , 
0, 52.5352, 1, 0, 0.515361,0.000300418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979961,-0.0196584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204845,0.000103496) , 
0, 241.55, 1, 0, 0.1748,-0.013628) , 
0, 220.008, 1, 0, 0.507987,-1.17186e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512614,-1.32823e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269083,0.00983218) , 
0, 242.865, 1, 0, 0.510957,0.000176734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0749874,-0.0306309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187309,-0.00104533) , 
0, 296.237, 1, 0, 0.161587,-0.020782) , 
0, 276.181, 1, 0, 0.507987,-1.45824e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523182,8.46018e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377806,0.0110557) , 
0, 164.567, 1, 0, 0.522014,0.000429414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173821,-0.0241106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24621,0.00079006) , 
0, 180.918, 1, 0, 0.237945,-0.00830278) , 
0, 173.198, 1, 0, 0.507987,-1.76733e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515894,7.09341e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298482,0.0135616) , 
0, 211.83, 1, 0, 0.514848,0.000273524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0734225,-0.0271093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209133,0.00103534) , 
0, 242.941, 1, 0, 0.175693,-0.0133627) , 
0, 224.689, 1, 0, 0.507987,-2.33428e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-3.31937e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0223607) , 
0, 312.292, 1, 0, 0.509429,0.000112232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.00449684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0258368) , 
0, 361.707, 1, 0, 0.111117,-0.0316825) , 
0, 327.672, 1, 0, 0.507987,-2.88166e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512649,-7.46151e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363232,0.0342821) , 
0, 242.667, 1, 0, 0.512344,0.000218883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18144,-0.00931482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190614,0.00349233) , 
0, 314.765, 1, 0, 0.184698,-0.0164596) , 
0, 252.775, 1, 0, 0.507987,-2.89871e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52006,-1.32852e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399144,0.0181407) , 
0, 180.684, 1, 0, 0.519391,0.000372942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235468,-0.00422262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206232,2.59758e-05) , 
0, 243.494, 1, 0, 0.224015,-0.0093693) , 
0, 187.241, 1, 0, 0.507987,-3.20417e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544704,-0.000118713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564648,0.0116087) , 
0, 97.8538, 1, 0, 0.545203,0.000893325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.00541915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,7.92238e-06) , 
0, 111.326, 1, 0, 0.350249,-0.00380325) , 
0, 102.983, 1, 0, 0.507987,-3.22656e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000155322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439696,0.00179721) , 
0, 94.5466, 1, 0, 0.530763,0.000606909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0534886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000893535) , 
0, 139.763, 1, 0, 0.299406,-0.00558789) , 
0, 135.75, 1, 0, 0.507987,-2.93245e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624561,-0.000736428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499172,0.00134737) , 
0, 28.9944, 1, 0, 0.564722,0.00145551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465102,-0.00159819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373878,0.000286105) , 
0, 96.2133, 1, 0, 0.411234,-0.00249498) , 
0, 70.2154, 1, 0, 0.507987,-4.73915e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.000742616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.0102561) , 
0, 2.16203, 1, 0, 0.679335,0.00372145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00431577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-1.12185e-05) , 
0, 18.6727, 1, 0, 0.455586,-0.00114365) , 
0, 4.68103, 1, 0, 0.507987,-4.26062e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528307,-9.01437e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470498,0.0111621) , 
0, 140.797, 1, 0, 0.527274,0.000541408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.01114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.000901627) , 
0, 153.74, 1, 0, 0.274076,-0.00661554) , 
0, 149.793, 1, 0, 0.507987,-3.77178e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620433,-0.000654505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578546,0.00877509) , 
0, 30.9257, 1, 0, 0.61558,0.00241378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479721,-0.00257423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435091,-2.67356e-05) , 
0, 46.4412, 1, 0, 0.440006,-0.00153109) , 
0, 37.4482, 1, 0, 0.507987,-3.6709e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651748,-0.0005275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572347,0.0103042) , 
0, 17.204, 1, 0, 0.643597,0.00317013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455091,-0.00951517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45043,7.9132e-05) , 
0, 28.0115, 1, 0, 0.450598,-0.00134608) , 
0, 23.4051, 1, 0, 0.507987,-3.16561e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676854,0.00100473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420831,-0.0198191) , 
0, 8.70687, 1, 0, 0.675438,0.00384865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45059,-0.0056347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45431,-3.02513e-05) , 
0, 18.6382, 1, 0, 0.454164,-0.0012407) , 
0, 9.36205, 1, 0, 0.507987,-2.76241e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.000508085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0112647) , 
0, 6.51852, 1, 0, 0.675438,0.00346396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45059,-0.00507397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45431,-2.7226e-05) , 
0, 18.6382, 1, 0, 0.454164,-0.00111665) , 
0, 9.36205, 1, 0, 0.507987,-2.46301e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557263,-8.28051e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513013,0.00525955) , 
0, 77.1309, 1, 0, 0.554604,0.00120022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416685,-0.00640398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388186,-8.63929e-05) , 
0, 88.5237, 1, 0, 0.390586,-0.00303032) , 
0, 84.2585, 1, 0, 0.507987,-2.173e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543405,4.38445e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514855,0.0131309) , 
0, 105.432, 1, 0, 0.543122,0.000851874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374692,-0.00281456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309052,0.000932862) , 
0, 140.855, 1, 0, 0.339423,-0.00409869) , 
0, 107.664, 1, 0, 0.507987,-2.02055e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000131674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439696,0.00169352) , 
0, 94.5466, 1, 0, 0.530763,0.000632469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0504676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000598262) , 
0, 139.763, 1, 0, 0.299406,-0.00581212) , 
0, 135.75, 1, 0, 0.507987,-1.96235e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523162,2.76338e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522206,0.0265678) , 
0, 165.159, 1, 0, 0.523159,0.000454596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233403,-0.0115101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245377,0.00011151) , 
0, 180.075, 1, 0, 0.24322,-0.00800148) , 
0, 168.517, 1, 0, 0.507987,-3.71461e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571891,0.000506267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408426,-0.0131789) , 
0, 64.2242, 1, 0, 0.569799,0.00153056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468547,-0.0018579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402369,-8.64054e-05) , 
0, 78.6087, 1, 0, 0.41638,-0.0022776) , 
0, 65.5344, 1, 0, 0.507987,-3.73406e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58843,0.000606692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437956,-0.000508725) , 
0, 52.5352, 1, 0, 0.515361,0.000269018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979961,-0.0169125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204845,-0.000442456) , 
0, 241.55, 1, 0, 0.1748,-0.0123119) , 
0, 220.008, 1, 0, 0.507987,-3.39466e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-1.91258e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0194723) , 
0, 312.292, 1, 0, 0.509429,0.000104523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131381,-0.0144575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772229,-0.00783501) , 
0, 383.045, 1, 0, 0.111117,-0.0296893) , 
0, 327.672, 1, 0, 0.507987,-3.34571e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511354,1.18231e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288489,0.0168255) , 
0, 266.192, 1, 0, 0.510957,0.000161833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.121168,-0.0184262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191268,0.0018268) , 
0, 312.767, 1, 0, 0.161587,-0.0192474) , 
0, 276.181, 1, 0, 0.507987,-3.18494e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512649,-6.4182e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363232,0.0296125) , 
0, 242.667, 1, 0, 0.512344,0.000197233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18144,-0.00841918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190614,0.00291854) , 
0, 314.765, 1, 0, 0.184698,-0.0148748) , 
0, 252.775, 1, 0, 0.507987,-3.18667e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58901,0.000608929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43502,-0.000523417) , 
0, 52.3838, 1, 0, 0.51364,0.00022432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0571171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204409,-0.000450789) , 
0, 241.122, 1, 0, 0.185215,-0.0129998) , 
0, 234.051, 1, 0, 0.507987,-3.31691e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-9.41584e-07) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.017128) , 
0, 312.292, 1, 0, 0.509429,9.69341e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.00355746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0242483) , 
0, 361.707, 1, 0, 0.111117,-0.0277345) , 
0, 327.672, 1, 0, 0.507987,-3.83004e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512671,-4.71072e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291388,0.0115355) , 
0, 242.445, 1, 0, 0.51172,0.000162455) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163147,-0.00967072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191299,0.00149181) , 
0, 312.907, 1, 0, 0.175571,-0.0147957) , 
0, 262.138, 1, 0, 0.507987,-3.67359e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624268,-0.000771767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457709,0.000427619) , 
0, 29.1021, 1, 0, 0.51364,0.000204587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0563487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204409,-0.000454051) , 
0, 241.122, 1, 0, 0.185215,-0.011885) , 
0, 234.051, 1, 0, 0.507987,-3.52053e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.0007744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00802204) , 
0, 0.0230003, 1, 0, 0.679335,0.00289169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495302,-0.00233577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450403,0.000105768) , 
0, 27.988, 1, 0, 0.455586,-0.000889464) , 
0, 4.68103, 1, 0, 0.507987,-3.93298e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651748,-0.000625312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572347,0.00965222) , 
0, 17.204, 1, 0, 0.643597,0.00244592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455091,-0.0084057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45043,0.000101997) , 
0, 28.0115, 1, 0, 0.450598,-0.00104006) , 
0, 23.4051, 1, 0, 0.507987,-3.48689e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.000551379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.0100086) , 
0, 2.16203, 1, 0, 0.679335,0.00287638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495302,-0.00217274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450403,8.5103e-05) , 
0, 27.988, 1, 0, 0.455586,-0.000883641) , 
0, 4.68103, 1, 0, 0.507987,-3.05851e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544571,-7.45286e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576866,0.0114751) , 
0, 98.8784, 1, 0, 0.545203,0.000770173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.00550476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,0.000165155) , 
0, 111.326, 1, 0, 0.350249,-0.00327851) , 
0, 102.983, 1, 0, 0.507987,-2.6995e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620433,-0.000602284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578546,0.00768678) , 
0, 30.9257, 1, 0, 0.61558,0.00199289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479721,-0.00254127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435091,3.18682e-05) , 
0, 46.4412, 1, 0, 0.440006,-0.00126314) , 
0, 37.4482, 1, 0, 0.507987,-2.43431e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651748,-0.000522077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572347,0.00897852) , 
0, 17.204, 1, 0, 0.643597,0.00250883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455091,-0.00728294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45043,5.31594e-05) , 
0, 28.0115, 1, 0, 0.450598,-0.00106468) , 
0, 23.4051, 1, 0, 0.507987,-2.07348e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.000436917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0107093) , 
0, 6.51852, 1, 0, 0.675438,0.00309248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493495,-0.00236746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447543,0.000170382) , 
0, 32.5414, 1, 0, 0.454164,-0.000996373) , 
0, 9.36205, 1, 0, 0.507987,-1.7979e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557263,-8.96863e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513013,0.00480002) , 
0, 77.1309, 1, 0, 0.554604,0.00103256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416685,-0.00574428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388186,-5.16564e-05) , 
0, 88.5237, 1, 0, 0.390586,-0.0026059) , 
0, 84.2585, 1, 0, 0.507987,-1.55802e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564791,0.000202934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548742,0.0151709) , 
0, 69.866, 1, 0, 0.564722,0.00128784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465102,-0.00143681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373878,0.000273335) , 
0, 96.2133, 1, 0, 0.411234,-0.00220017) , 
0, 70.2154, 1, 0, 0.507987,-1.45956e-06)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,-1.47862e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.0158033) , 
0, 146.012, 1, 0, 0.527274,0.000462323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27275,-0.0102699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274174,-0.000709463) , 
0, 153.74, 1, 0, 0.274076,-0.00562448) , 
0, 149.793, 1, 0, 0.507987,-1.33908e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.000770729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00795564) , 
0, 0.0230003, 1, 0, 0.679335,0.00287933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00300396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-2.69788e-05) , 
0, 18.6727, 1, 0, 0.455586,-0.000882327) , 
0, 4.68103, 1, 0, 0.507987,-1.36093e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544704,-8.49728e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564648,0.00919672) , 
0, 97.8538, 1, 0, 0.545203,0.000748899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.00500455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,9.51937e-05) , 
0, 111.326, 1, 0, 0.350249,-0.0031804) , 
0, 102.983, 1, 0, 0.507987,-1.18352e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556991,-2.67418e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622068,0.0149975) , 
0, 77.9876, 1, 0, 0.558035,0.00106561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00309155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,1.32469e-05) , 
0, 88.1696, 1, 0, 0.396907,-0.00236857) , 
0, 79.5775, 1, 0, 0.507987,-1.07044e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564791,0.000193808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548742,0.013649) , 
0, 69.866, 1, 0, 0.564722,0.00121209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465102,-0.00128987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373878,0.000209394) , 
0, 96.2133, 1, 0, 0.411234,-0.00206938) , 
0, 70.2154, 1, 0, 0.507987,-8.63847e-07)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.0001166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439696,0.00144165) , 
0, 94.5466, 1, 0, 0.530763,0.000519919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0478636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000665299) , 
0, 139.763, 1, 0, 0.299406,-0.00476946) , 
0, 135.75, 1, 0, 0.507987,-7.89517e-07)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525323,-2.84393e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434628,0.0163867) , 
0, 154.353, 1, 0, 0.52466,0.000416412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304233,-0.0047558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243425,-0.000141943) , 
0, 178.699, 1, 0, 0.260706,-0.00621552) , 
0, 159.155, 1, 0, 0.507987,-2.50242e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528307,-7.09743e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470498,0.00911406) , 
0, 140.797, 1, 0, 0.527274,0.000459214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31977,-0.0060014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262005,2.20909e-05) , 
0, 161.611, 1, 0, 0.274076,-0.00560269) , 
0, 149.793, 1, 0, 0.507987,-2.55153e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543405,2.54912e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514855,0.0125218) , 
0, 105.432, 1, 0, 0.543122,0.000735251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364992,-0.00680801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337669,-0.000356979) , 
0, 111.839, 1, 0, 0.339423,-0.00354179) , 
0, 107.664, 1, 0, 0.507987,-2.47037e-06)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571891,0.000436506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408426,-0.0118635) , 
0, 64.2242, 1, 0, 0.569799,0.00128751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468547,-0.00168254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402369,-3.79536e-05) , 
0, 78.6087, 1, 0, 0.41638,-0.0019139) , 
0, 65.5344, 1, 0, 0.507987,-2.33034e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544571,-3.17388e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576866,0.00923264) , 
0, 98.8784, 1, 0, 0.545203,0.000750581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.00482139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,5.61102e-05) , 
0, 111.326, 1, 0, 0.350249,-0.00319251) , 
0, 102.983, 1, 0, 0.507987,-2.13476e-06)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557263,-8.24294e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513013,0.00447922) , 
0, 77.1309, 1, 0, 0.554604,0.00096806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416685,-0.00458004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388186,-0.00013016) , 
0, 88.5237, 1, 0, 0.390586,-0.00244473) , 
0, 84.2585, 1, 0, 0.507987,-1.91754e-06)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613298,0.000688489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439839,-0.000411071) , 
0, 39.0365, 1, 0, 0.509429,9.04386e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131381,-0.0131454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772229,-0.00550709) , 
0, 383.045, 1, 0, 0.111117,-0.0253772) , 
0, 327.672, 1, 0, 0.507987,-1.76754e-06)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520039,-2.51739e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609704,0.0645741) , 
0, 180.702, 1, 0, 0.520172,0.000299533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295203,-0.00714984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223257,-0.000831858) , 
0, 190.131, 1, 0, 0.233244,-0.00679244) , 
0, 182.56, 1, 0, 0.507987,-1.64725e-06)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535395,0.00018531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34397,-0.00349873) , 
0, 125.612, 1, 0, 0.530763,0.000479879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0453605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000567569) , 
0, 139.763, 1, 0, 0.299406,-0.0044191) , 
0, 135.75, 1, 0, 0.507987,-2.39642e-06)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523182,-3.53252e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377806,0.00998069) , 
0, 164.567, 1, 0, 0.522014,0.00033573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136617,-0.0304858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2445,0.000128316) , 
0, 177.099, 1, 0, 0.237945,-0.00654041) , 
0, 173.198, 1, 0, 0.507987,-3.80232e-06)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,-8.37189e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.0131928) , 
0, 146.012, 1, 0, 0.527274,0.000406767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31977,-0.00538935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262005,2.83283e-05) , 
0, 161.611, 1, 0, 0.274076,-0.00498645) , 
0, 149.793, 1, 0, 0.507987,-4.06079e-06)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512549,-3.39233e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381994,0.0278775) , 
0, 245.181, 1, 0, 0.512344,0.000157453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18144,-0.00734488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190614,0.00338115) , 
0, 314.765, 1, 0, 0.184698,-0.0119654) , 
0, 252.775, 1, 0, 0.507987,-3.74987e-06)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509587,-1.67511e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,0.0150009) , 
0, 312.292, 1, 0, 0.509429,8.20363e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196999,-0.00241818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495922,-0.0225604) , 
0, 361.707, 1, 0, 0.111117,-0.0235936) , 
0, 327.672, 1, 0, 0.507987,-3.68188e-06)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525323,-3.73942e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434628,0.0158798) , 
0, 154.353, 1, 0, 0.52466,0.000358188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304233,-0.00407852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243425,-0.000148859) , 
0, 178.699, 1, 0, 0.260706,-0.00536773) , 
0, 159.155, 1, 0, 0.507987,-3.49682e-06)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540568,-6.19218e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403631,0.00215554) , 
0, 111.43, 1, 0, 0.530763,0.000457961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0430539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000450811) , 
0, 139.763, 1, 0, 0.299406,-0.00422874) , 
0, 135.75, 1, 0, 0.507987,-3.41615e-06)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528307,-5.71834e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470498,0.00765704) , 
0, 140.797, 1, 0, 0.527274,0.000399666) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31977,-0.00552167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262005,9.78475e-05) , 
0, 161.611, 1, 0, 0.274076,-0.0049069) , 
0, 149.793, 1, 0, 0.507987,-4.56146e-06)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520181,-2.09174e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390718,0.014058) , 
0, 179.753, 1, 0, 0.519391,0.00027823) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275937,-0.0041433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199574,-0.000734283) , 
0, 209.75, 1, 0, 0.224015,-0.0070375) , 
0, 187.241, 1, 0, 0.507987,-4.22976e-06)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523182,-2.94843e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377806,0.00929531) , 
0, 164.567, 1, 0, 0.522014,0.000315667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173821,-0.0202369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24621,0.000787369) , 
0, 180.918, 1, 0, 0.237945,-0.00615854) , 
0, 173.198, 1, 0, 0.507987,-4.0184e-06)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520039,-1.50384e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609704,0.0538317) , 
0, 180.702, 1, 0, 0.520172,0.000295611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295203,-0.0073998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223257,-0.000768083) , 
0, 190.131, 1, 0, 0.233244,-0.00676283) , 
0, 182.56, 1, 0, 0.507987,-4.14494e-06)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549777,0.000333562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431705,-0.00112632) , 
0, 91.1699, 1, 0, 0.530763,0.000458289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0408623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000298206) , 
0, 139.763, 1, 0, 0.299406,-0.00424052) , 
0, 135.75, 1, 0, 0.507987,-4.28099e-06)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525323,-3.07073e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434628,0.0146809) , 
0, 154.353, 1, 0, 0.52466,0.000352571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318733,-0.00416328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242768,-0.000353215) , 
0, 174.81, 1, 0, 0.260706,-0.00531087) , 
0, 159.155, 1, 0, 0.507987,-5.16733e-06)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,5.84464e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.011014) , 
0, 146.012, 1, 0, 0.527274,0.000401645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31977,-0.00557479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262005,0.000104824) , 
0, 161.611, 1, 0, 0.274076,-0.00493488) , 
0, 149.793, 1, 0, 0.507987,-4.86416e-06)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612118,0.000583668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439686,-0.000351907) , 
0, 39.5387, 1, 0, 0.509575,8.64005e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182583,-0.00877245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772229,-0.00318261) , 
0, 384.064, 1, 0, 0.150286,-0.0204759) , 
0, 318.31, 1, 0, 0.507987,-4.46537e-06)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624268,-0.00072374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457709,0.000393138) , 
0, 29.1021, 1, 0, 0.51364,0.00016562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0556659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204409,-4.6696e-05) , 
0, 241.122, 1, 0, 0.185215,-0.00969096) , 
0, 234.051, 1, 0, 0.507987,-4.04917e-06)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612118,0.000575771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439686,-0.000349918) , 
0, 39.5387, 1, 0, 0.509575,7.74178e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238202,-0.00233908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0505318,-0.0201567) , 
0, 362.41, 1, 0, 0.150286,-0.018425) , 
0, 318.31, 1, 0, 0.507987,-4.34552e-06)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545939,-0.000152742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439696,0.00144508) , 
0, 94.5466, 1, 0, 0.530763,0.000373318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0387544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000362561) , 
0, 139.763, 1, 0, 0.299406,-0.00345953) , 
0, 135.75, 1, 0, 0.507987,-4.00408e-06)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523162,-1.45795e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522206,0.0228423) , 
0, 165.159, 1, 0, 0.523159,0.000273824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235744,-0.0104544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244371,0.000225252) , 
0, 176.233, 1, 0, 0.24322,-0.00486661) , 
0, 168.517, 1, 0, 0.507987,-4.78263e-06)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528307,-5.0059e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470498,0.00641856) , 
0, 140.797, 1, 0, 0.527274,0.00032646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31977,-0.00504074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262005,0.000240119) , 
0, 161.611, 1, 0, 0.274076,-0.0040189) , 
0, 149.793, 1, 0, 0.507987,-4.54782e-06)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520039,-1.90772e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609704,0.0470118) , 
0, 180.702, 1, 0, 0.520172,0.000238708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295203,-0.00675027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223257,-0.00047303) , 
0, 190.131, 1, 0, 0.233244,-0.00548089) , 
0, 182.56, 1, 0, 0.507987,-4.19072e-06)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523673,-2.19073e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376553,0.00730023) , 
0, 161.983, 1, 0, 0.522014,0.000263752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173821,-0.0185213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24621,0.000815476) , 
0, 180.918, 1, 0, 0.237945,-0.00516124) , 
0, 173.198, 1, 0, 0.507987,-4.12555e-06)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565742,7.03107e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507388,0.00641674) , 
0, 68.818, 1, 0, 0.564722,0.000887782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465102,-0.00105172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373878,0.000232584) , 
0, 96.2133, 1, 0, 0.411234,-0.00152523) , 
0, 70.2154, 1, 0, 0.507987,-4.15928e-06)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624452,-0.000682907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476774,0.00048567) , 
0, 29.0393, 1, 0, 0.530763,0.000391052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690261,-0.0367521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30937,0.000200303) , 
0, 139.763, 1, 0, 0.299406,-0.0036195) , 
0, 135.75, 1, 0, 0.507987,-3.76325e-06)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678975,0.000413939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711577,0.00981002) , 
0, 2.16203, 1, 0, 0.679335,0.00226937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00277736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,3.26484e-07) , 
0, 18.6727, 1, 0, 0.455586,-0.000699755) , 
0, 4.68103, 1, 0, 0.507987,-4.39767e-06)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525323,-3.69957e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434628,0.0141954) , 
0, 154.353, 1, 0, 0.52466,0.000307357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318733,-0.00406618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242768,-0.000143148) , 
0, 174.81, 1, 0, 0.260706,-0.00462056) , 
0, 159.155, 1, 0, 0.507987,-3.92119e-06)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527245,6.73375e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53154,0.00921622) , 
0, 146.012, 1, 0, 0.527274,0.00034528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31977,-0.00513801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262005,0.000197083) , 
0, 161.611, 1, 0, 0.274076,-0.00423642) , 
0, 149.793, 1, 0, 0.507987,-3.73074e-06)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651748,-0.000614083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572347,0.00836859) , 
0, 17.204, 1, 0, 0.643597,0.00182941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455091,-0.00639832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45043,8.03674e-05) , 
0, 28.0115, 1, 0, 0.450598,-0.000779067) , 
0, 23.4051, 1, 0, 0.507987,-3.4219e-06)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676605,0.00026794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626806,0.0102136) , 
0, 6.51852, 1, 0, 0.675438,0.00230894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493495,-0.00217274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447543,0.000197358) , 
0, 32.5414, 1, 0, 0.454164,-0.00074613) , 
0, 9.36205, 1, 0, 0.507987,-3.01236e-06)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620433,-0.000550213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578546,0.006683) , 
0, 30.9257, 1, 0, 0.61558,0.00162053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479721,-0.00241318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435091,7.06091e-05) , 
0, 46.4412, 1, 0, 0.440006,-0.00102825) , 
0, 37.4482, 1, 0, 0.507987,-2.66222e-06)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679921,0.000671757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634203,-0.00799148) , 
0, 0.0230003, 1, 0, 0.679335,0.00244779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48107,-0.00251243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454216,-2.57015e-05) , 
0, 18.6727, 1, 0, 0.455586,-0.000751575) , 
0, 4.68103, 1, 0, 0.507987,-2.29667e-06)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571891,0.000371406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408426,-0.0106987) , 
0, 64.2242, 1, 0, 0.569799,0.0010572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468547,-0.00158233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402369,2.66817e-05) , 
0, 78.6087, 1, 0, 0.41638,-0.00157182) , 
0, 65.5344, 1, 0, 0.507987,-2.02393e-06)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55728,-0.000100026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589058,0.0111332) , 
0, 77.1958, 1, 0, 0.558035,0.000845479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439682,-0.00256722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388885,3.23947e-05) , 
0, 88.1696, 1, 0, 0.396907,-0.00188251) , 
0, 79.5775, 1, 0, 0.507987,-1.85533e-06)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544704,-6.68066e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564648,0.00737888) , 
0, 97.8538, 1, 0, 0.545203,0.000605743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410584,-0.00438161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,0.000138447) , 
0, 111.326, 1, 0, 0.350249,-0.0025759) , 
0, 102.983, 1, 0, 0.507987,-1.6161e-06)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574364,-8.23427e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48434,0.00247285) , 
0, 60.4341, 1, 0, 0.564722,0.000972361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465102,-0.0010007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373878,0.000141181) , 
0, 96.2133, 1, 0, 0.411234,-0.00166215) , 
0, 70.2154, 1, 0, 0.507987,-1.45439e-06)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543405,-5.7662e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514855,0.0121341) , 
0, 105.432, 1, 0, 0.543122,0.000567909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364992,-0.0054909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337669,-0.000261388) , 
0, 111.839, 1, 0, 0.339423,-0.00273232) , 
0, 107.664, 1, 0, 0.507987,-1.32797e-06)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571891,0.000347625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408426,-0.00987281) , 
0, 64.2242, 1, 0, 0.569799,0.000999295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468547,-0.00156611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402369,4.5954e-05) , 
0, 78.6087, 1, 0, 0.41638,-0.00148416) , 
0, 65.5344, 1, 0, 0.507987,-1.28356e-06)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517201,-8.69054e-07) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351401,0.0173004) , 
0, 200.721, 1, 0, 0.516713,0.000201747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181838,-0.00652108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2082,0.000895116) , 
0, 242.596, 1, 0, 0.196645,-0.00724146) , 
0, 205.965, 1, 0, 0.507987,-1.18782e-06)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549828,0.00029596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387108,-0.000882057) , 
0, 90.7751, 1, 0, 0.510838,0.00010803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116488,-0.0189068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195838,0.00538977) , 
0, 313.721, 1, 0, 0.162856,-0.0132369) , 
0, 280.862, 1, 0, 0.507987,-1.30822e-06)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612118,0.000524891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439686,-0.000315098) , 
0, 39.5387, 1, 0, 0.509575,8.1928e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182583,-0.00835576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772229,-0.00174485) , 
0, 384.064, 1, 0, 0.150286,-0.0187801) , 
0, 318.31, 1, 0, 0.507987,-1.42414e-06)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527384,7.03103e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253907,-0.0185987) , 
0, 149.024, 1, 0, 0.525173,-0.00032232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469811,0.0208322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261212,-0.00114068) , 
0, 158.388, 1, 0, 0.278787,0.00427969) , 
0, 154.474, 1, 0, 0.507987,-1.31136e-06)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600629,0.000231104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4276,-0.0126417) , 
0, 44.7143, 1, 0, 0.594405,-0.00123646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515152,0.00405178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429691,-4.62022e-05) , 
0, 51.2595, 1, 0, 0.434955,0.00104151) , 
0, 46.8103, 1, 0, 0.507987,-1.85953e-06)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510166,-4.42823e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254633,0.012187) , 
0, 292.587, 1, 0, 0.509575,7.19827e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238202,-0.00199695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0505318,-0.0190235) , 
0, 362.41, 1, 0, 0.150286,-0.0166034) , 
0, 318.31, 1, 0, 0.507987,-1.70655e-06)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510928,2.3449e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110792,-0.0196131) , 
0, 277.41, 1, 0, 0.509489,-8.06556e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369058,0.0173282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0788121,-0.0118124) , 
0, 338.844, 1, 0, 0.195838,0.0164123) , 
0, 313.629, 1, 0, 0.507987,-1.69077e-06)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527022,4.45008e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215955,-0.0204982) , 
0, 150.56, 1, 0, 0.525173,-0.000300756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469811,0.0185506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261212,-0.000989379) , 
0, 158.388, 1, 0, 0.278787,0.00398351) , 
0, 154.474, 1, 0, 0.507987,-1.91082e-06)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510166,-5.29646e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254633,0.0122628) , 
0, 292.587, 1, 0, 0.509575,6.80603e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248032,-0.00795114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.084998,-0.00338678) , 
0, 343.849, 1, 0, 0.150286,-0.015862) , 
0, 318.31, 1, 0, 0.507987,-2.33543e-06)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510928,2.10719e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110792,-0.0186588) , 
0, 277.41, 1, 0, 0.509489,-7.93353e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369058,0.0159132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0788121,-0.0104219) , 
0, 338.844, 1, 0, 0.195838,0.0160331) , 
0, 313.629, 1, 0, 0.507987,-2.19209e-06)    );
   return;
};

// Clean up
inline void Readall_SR__tZq::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double Readall_SR__tZq::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
