// Class: Readall_SR__tZq
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::all_SR__tZq
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : ntonon
Date           : Wed Jan 15 17:32:53 2020
Host           : Linux cmspcx36679 4.15.0-1065-oem #75-Ubuntu SMP Wed Nov 20 10:51:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ntonon/Postdoc/EFTSimulations/myAnalysis
Training events: 53211
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
DoBoostMonitor: "True" [Create control plot with ROC integral vs tree number]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
metEt                         metEt                         metEt                         metEt                                                           'F'    [0.237109705806,940.886535645]
maxEtaJet                     maxEtaJet                     maxEtaJet                     maxEtaJet                                                       'F'    [0.0219132117927,4.88331365585]
leptonCharge                  leptonCharge                  leptonCharge                  leptonCharge                                                    'F'    [-1,1]
m3l                           m3l                           m3l                           m3l                                                             'F'    [84.2761764526,1546.06323242]
maxDijetDelR                  maxDijetDelR                  maxDijetDelR                  maxDijetDelR                                                    'F'    [0.433118790388,9.68713665009]
deepCSV_2nd                   deepCSV_2nd                   deepCSV_2nd                   deepCSV_2nd                                                     'F'    [-9,0.999581634998]
dEtaFwdJetBJet                dEtaFwdJetBJet                dEtaFwdJetBJet                dEtaFwdJetBJet                                                  'F'    [0,6.50128698349]
dEtaFwdJetClosestLep          dEtaFwdJetClosestLep          dEtaFwdJetClosestLep          dEtaFwdJetClosestLep                                            'F'    [1.72853469849e-06,5.78053808212]
mHT                           mHT                           mHT                           mHT                                                             'F'    [141.131958008,3875.37939453]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new all_SR__tZqNode

#ifndef all_SR__tZqNode__def
#define all_SR__tZqNode__def

class all_SR__tZqNode {

public:

   // constructor of an essentially "empty" node floating in space
   all_SR__tZqNode ( all_SR__tZqNode* left,all_SR__tZqNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~all_SR__tZqNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   all_SR__tZqNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   all_SR__tZqNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   all_SR__tZqNode*   fLeft;     // pointer to the left daughter node
   all_SR__tZqNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   all_SR__tZqNode::~all_SR__tZqNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool all_SR__tZqNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool all_SR__tZqNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Readall_SR__tZq : public IClassifierReader {

 public:

   // constructor
   Readall_SR__tZq( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "Readall_SR__tZq" ),
        fNvars( 9 )
   {
      // the training input variables
      const char* inputVars[] = { "metEt", "maxEtaJet", "leptonCharge", "m3l", "maxDijetDelR", "deepCSV_2nd", "dEtaFwdJetBJet", "dEtaFwdJetClosestLep", "mHT" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Readall_SR__tZq() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<all_SR__tZqNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Readall_SR__tZq::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      all_SR__tZqNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(all_SR__tZqNode*)current->GetRight();
         else current=(all_SR__tZqNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void Readall_SR__tZq::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981633,0.0963265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873592,0.0747185) , 
8, 477.021, 1, 0, 0.954993,0.454993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286271,-0.0427458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726525,0.0453049) , 
6, 2.1671, 1, 0, 0.381925,-0.118075) , 
7, 0.0287606, 1, 0, 0.5,-4.59759e-17)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98091,0.0878612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878001,0.0670147) , 
7, 0.00843683, 1, 0, 0.954993,0.409622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297257,-0.0367349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765317,0.0486357) , 
6, 2.39351, 1, 0, 0.381925,-0.106274) , 
7, 0.0287606, 1, 0, 0.5,2.11485e-05)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.973998,0.0798023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739954,0.0424029) , 
7, 0.0128755, 1, 0, 0.921483,0.346815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269945,-0.0383206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694475,0.0330014) , 
6, 2.00537, 1, 0, 0.37538,-0.102426) , 
7, 0.0575195, 1, 0, 0.5,9.00839e-05)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964427,0.0742983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769641,0.0375265) , 
8, 513.118, 1, 0, 0.921483,0.312622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71253,0.0459622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303398,-0.0324975) , 
5, -1.98537, 1, 0, 0.37538,-0.0922241) , 
7, 0.0575195, 1, 0, 0.5,0.000161104)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982615,0.0721463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877443,0.0520763) , 
8, 464.989, 1, 0, 0.954993,0.302546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298913,-0.0285132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771281,0.0429869) , 
6, 2.42585, 1, 0, 0.381925,-0.0782162) , 
7, 0.0287606, 1, 0, 0.5,0.000236247)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549223,0.00867472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.831064,0.0565569) , 
4, 3.45867, 1, 0, 0.707799,0.165698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.889701,0.0505455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278959,-0.0339106) , 
7, 0.0287663, 1, 0, 0.345708,-0.122452) , 
8, 438.385, 1, 0, 0.5,0.000332719)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966967,0.0634189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581649,0.0193093) , 
7, 0.0186016, 1, 0, 0.84257,0.209459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24295,-0.0345556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663001,0.0256471) , 
6, 1.84365, 1, 0, 0.364768,-0.0822138) , 
7, 0.143796, 1, 0, 0.5,0.000338524)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568286,0.0100353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.839856,0.0536922) , 
1, 2.17103, 1, 0, 0.725347,0.15767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896924,0.0448257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287291,-0.0283909) , 
7, 0.0287663, 1, 0, 0.357439,-0.0991143) , 
8, 419.807, 1, 0, 0.5,0.000387056)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665044,0.0264033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891997,0.061067) , 
4, 3.2007, 1, 0, 0.815796,0.217993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93357,0.0506376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309346,-0.0233125) , 
7, 0.0287632, 1, 0, 0.410566,-0.0612297) , 
5, -1.98537, 1, 0, 0.5,0.00039451)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52344,0.00236758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808626,0.0451691) , 
4, 3.55035, 1, 0, 0.678058,0.110197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246241,-0.0350627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531236,0.00569762) , 
6, 1.67876, 1, 0, 0.325211,-0.107291) , 
8, 475.542, 1, 0, 0.5,0.000445288)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876324,0.0533403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577454,0.0105579) , 
7, 0.61564, 1, 0, 0.76504,0.153286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730751,0.0246673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292579,-0.0238629) , 
7, 0.143799, 1, 0, 0.382865,-0.0671609) , 
8, 382.65, 1, 0, 0.5,0.000405029)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63042,0.0182618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877998,0.0527859) , 
1, 1.77012, 1, 0, 0.815796,0.183176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714253,0.0235751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286526,-0.0240256) , 
7, 0.230075, 1, 0, 0.410566,-0.051354) , 
5, -1.98537, 1, 0, 0.5,0.000406547)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52224,0.000220175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796038,0.0416311) , 
4, 3.92294, 1, 0, 0.641375,0.0749001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215369,-0.0363225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440747,-0.00331192) , 
6, 1.34583, 1, 0, 0.296803,-0.106678) , 
8, 531.277, 1, 0, 0.5,0.00039987)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665044,0.0203226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891997,0.0505933) , 
4, 3.2007, 1, 0, 0.815796,0.160723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93357,0.0443119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309346,-0.0180329) , 
7, 0.0287632, 1, 0, 0.410566,-0.04506) , 
5, -1.98537, 1, 0, 0.5,0.000356106)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880042,0.0472383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578564,0.00791329) , 
7, 0.587657, 1, 0, 0.76504,0.119854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342247,-0.0180375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794942,0.0444756) , 
6, 2.8824, 1, 0, 0.382865,-0.0523955) , 
8, 382.65, 1, 0, 0.5,0.000398225)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792305,0.0336393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430525,-0.00520707) , 
8, 640.164, 1, 0, 0.719153,0.0938925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211456,-0.030958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668659,0.0224182) , 
6, 1.87599, 1, 0, 0.352831,-0.0623756) , 
7, 0.373867, 1, 0, 0.5,0.000404577)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741673,0.0231452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891302,0.0483668) , 
6, 1.29379, 1, 0, 0.815796,0.13606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93357,0.0402998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309346,-0.0155011) , 
7, 0.0287632, 1, 0, 0.410566,-0.0380826) , 
5, -1.98537, 1, 0, 0.5,0.000350599)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469801,-0.00718687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744829,0.0305902) , 
4, 3.55559, 1, 0, 0.620947,0.050891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430103,-0.00269842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194784,-0.0324661) , 
7, 0.471047, 1, 0, 0.280605,-0.0912535) , 
8, 568.434, 1, 0, 0.5,0.000377195)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478761,-0.00196187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753687,0.0314388) , 
1, 1.91198, 1, 0, 0.656278,0.0730601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285417,-0.0276135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503484,0.00593544) , 
4, 4.15253, 1, 0, 0.373902,-0.058358) , 
5, 0.0543475, 1, 0, 0.5,0.000328149)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.902017,0.0453927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544822,0.00698223) , 
8, 360.645, 1, 0, 0.663781,0.0666065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234069,-0.0265669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785905,0.0326656) , 
6, 2.55523, 1, 0, 0.347116,-0.0616104) , 
7, 0.546421, 1, 0, 0.5,0.000291899)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76613,0.0498096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787949,0.0205728) , 
6, 0.0970341, 1, 0, 0.783694,0.0981424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297373,-0.0214939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573403,0.0125404) , 
6, 1.42536, 1, 0, 0.3972,-0.0351789) , 
8, 364.072, 1, 0, 0.5,0.000281964)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980352,0.0523516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585905,0.00881844) , 
7, 0.00858494, 1, 0, 0.756091,0.078028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236016,-0.0214312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718016,0.0217696) , 
6, 2.13475, 1, 0, 0.356429,-0.0433626) , 
7, 0.287591, 1, 0, 0.5,0.000244616)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474314,-0.00135488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176536,-0.0398334) , 
7, 0.88117, 1, 0, 0.364878,-0.0634603) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719137,0.0246158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321689,-0.0123437) , 
8, 605.591, 1, 0, 0.601514,0.0481468) , 
1, 2.1261, 1, 0, 0.5,0.000268635)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56685,0.00592375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.80127,0.0335247) , 
6, 1.5202, 1, 0, 0.656278,0.060333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295568,-0.0228424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516827,0.00701572) , 
4, 4.33621, 1, 0, 0.373902,-0.0482819) , 
5, 0.0543475, 1, 0, 0.5,0.000221219)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635403,0.039586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614491,0.00792846) , 
6, 0.0252952, 1, 0, 0.617168,0.0459235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256902,-0.023683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.862335,0.0395782) , 
6, 3.07275, 1, 0, 0.346629,-0.0596527) , 
7, 0.747733, 1, 0, 0.5,0.00019937)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.855293,0.037329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753963,0.0143308) , 
2, -0.99005, 1, 0, 0.815796,0.0943871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284925,-0.0222658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504444,0.00460188) , 
4, 3.56383, 1, 0, 0.410566,-0.0265151) , 
5, -1.98537, 1, 0, 0.5,0.00016791)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412501,-0.0101548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695941,0.0190743) , 
1, 1.86005, 1, 0, 0.604037,0.0327753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331973,-0.00522295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18716,-0.0352897) , 
2, -0.99005, 1, 0, 0.266335,-0.0731057) , 
8, 605.591, 1, 0, 0.5,0.000156318)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97724,0.0487663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678389,0.00810433) , 
7, 0.0102991, 1, 0, 0.86477,0.0797806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236459,-0.0190783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584364,0.0116092) , 
6, 1.45551, 1, 0, 0.367939,-0.0287135) , 
7, 0.115037, 1, 0, 0.5,0.000124992)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80238,0.0462342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836946,0.0240192) , 
6, 0.323447, 1, 0, 0.827288,0.0977397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320421,-0.0168648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581646,0.00938957) , 
6, 1.29866, 1, 0, 0.425499,-0.0220615) , 
8, 326.915, 1, 0, 0.5,0.000152371)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630411,0.036972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608901,0.00672871) , 
6, 0.0252952, 1, 0, 0.611674,0.0396568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248572,-0.0222124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847111,0.0311111) , 
6, 2.97571, 1, 0, 0.347018,-0.0539979) , 
7, 0.776492, 1, 0, 0.5,0.000138379)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670462,0.0217278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529283,-0.00305042) , 
2, -0.99005, 1, 0, 0.611441,0.0392261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286551,-0.0217477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511447,0.00486062) , 
4, 4.52261, 1, 0, 0.355586,-0.0505755) , 
5, 0.104097, 1, 0, 0.5,0.000111972)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722099,0.018428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340539,-0.011631) , 
8, 732.13, 1, 0, 0.663781,0.0438578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171809,-0.0257811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587629,0.00801521) , 
6, 1.48786, 1, 0, 0.347116,-0.0407648) , 
7, 0.546421, 1, 0, 0.5,9.04496e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826705,0.0445152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.862672,0.0260242) , 
6, 0.485171, 1, 0, 0.850322,0.0971864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502798,0.00606515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354858,-0.0183845) , 
2, -0.99005, 1, 0, 0.43845,-0.0170082) , 
8, 308.337, 1, 0, 0.5,5.70378e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430369,-0.00766823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69204,0.0180628) , 
4, 3.55559, 1, 0, 0.575888,0.021377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275514,-0.0121856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134335,-0.0447132) , 
7, 1.42714, 1, 0, 0.243116,-0.0721119) , 
8, 679.904, 1, 0, 0.5,5.69449e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645203,0.0362957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607273,0.00599756) , 
6, 0.0323447, 1, 0, 0.611441,0.0339968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.912139,0.0240326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265372,-0.0156578) , 
7, 0.0279921, 1, 0, 0.355586,-0.0439638) , 
5, 0.104097, 1, 0, 0.5,4.01173e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596125,0.0301003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566313,0.00347109) , 
6, 0.026592, 1, 0, 0.570241,0.0260413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210405,-0.0253198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.799071,0.0195435) , 
6, 2.68461, 1, 0, 0.354347,-0.0539065) , 
7, 1.03532, 1, 0, 0.5,3.047e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98091,0.0476081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878001,0.00584519) , 
7, 0.00843683, 1, 0, 0.954993,0.0714152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263326,-0.0134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608727,0.0106442) , 
6, 1.55255, 1, 0, 0.381925,-0.0185213) , 
7, 0.0287606, 1, 0, 0.5,9.23561e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379066,-0.00801051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641786,0.0173069) , 
1, 1.87078, 1, 0, 0.560357,0.0309741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.943785,0.0300135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306037,-0.0164791) , 
7, 0.0279853, 1, 0, 0.420058,-0.0409159) , 
2, -0.99005, 1, 0, 0.5,4.68369e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741673,0.012357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891302,0.0342458) , 
6, 1.29379, 1, 0, 0.815796,0.066253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803483,0.0345769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374695,-0.00842706) , 
8, 301.48, 1, 0, 0.410566,-0.0187059) , 
5, -1.98537, 1, 0, 0.5,4.4437e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431495,-0.00289738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156586,-0.0368493) , 
7, 1.21161, 1, 0, 0.364878,-0.0385718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637541,0.0338972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596678,0.00467266) , 
6, 0.0323447, 1, 0, 0.601514,0.0290801) , 
1, 2.1261, 1, 0, 0.5,5.82296e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633884,0.0149027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480063,-0.00558924) , 
3, 193.365, 1, 0, 0.568596,0.0209665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21334,-0.027719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437757,-0.00368585) , 
4, 3.76725, 1, 0, 0.326792,-0.0528237) , 
5, 0.253344, 1, 0, 0.5,3.34623e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452173,-0.00278652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679713,0.0182182) , 
6, 1.34223, 1, 0, 0.529241,0.0151935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207479,-0.0304701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.815436,0.0155406) , 
6, 2.91102, 1, 0, 0.372432,-0.0661883) , 
7, 1.52422, 1, 0, 0.5,1.77663e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489739,0.00121774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706975,0.0234832) , 
4, 4.49109, 1, 0, 0.560357,0.027406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73086,0.0106396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305061,-0.0176022) , 
8, 372.178, 1, 0, 0.420058,-0.0362836) , 
2, -0.99005, 1, 0, 0.5,6.53225e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461549,-0.0039782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719248,0.0176119) , 
4, 3.92294, 1, 0, 0.575888,0.0168388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275514,-0.0102761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134335,-0.0388156) , 
7, 1.42714, 1, 0, 0.243116,-0.0569927) , 
8, 679.904, 1, 0, 0.5,1.57499e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981291,0.0457097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527172,0.00291455) , 
7, 0.00772766, 1, 0, 0.67132,0.0318649) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169029,-0.0219937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550104,0.0057664) , 
6, 1.29379, 1, 0, 0.348143,-0.0282553) , 
7, 0.517662, 1, 0, 0.5,-5.57332e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618001,0.0298511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586377,0.00332723) , 
6, 0.0323447, 1, 0, 0.589938,0.0223397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254458,-0.0201289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454729,-0.00119051) , 
1, 2.39185, 1, 0, 0.343475,-0.0388414) , 
5, 0.153846, 1, 0, 0.5,1.38896e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456278,-0.00356524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671066,0.0181369) , 
6, 1.09972, 1, 0, 0.560782,0.0239354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483081,-0.00219412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175535,-0.0391816) , 
7, 1.26539, 1, 0, 0.410478,-0.0352458) , 
3, 200.637, 1, 0, 0.5,2.90799e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431492,-0.00356778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728205,0.0177177) , 
6, 1.7652, 1, 0, 0.507732,0.00718358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37988,-0.033407) , 
7, 2.35823, 1, 0, 0.5,-9.92908e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826705,0.0376094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.862672,0.018589) , 
6, 0.485171, 1, 0, 0.850322,0.0671623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502798,0.00442374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354858,-0.0139087) , 
2, -0.99005, 1, 0, 0.43845,-0.0118063) , 
8, 308.337, 1, 0, 0.5,-5.16674e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873478,0.031793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791063,0.0135336) , 
3, 143.51, 1, 0, 0.815796,0.051756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448957,0.0167183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404905,-0.0078476) , 
6, 0.0316748, 1, 0, 0.410566,-0.0146591) , 
5, -1.98537, 1, 0, 0.5,-1.34394e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982404,0.045102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757759,0.00439816) , 
7, 0.00729821, 1, 0, 0.889562,0.0463209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452862,0.00404096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259007,-0.0163942) , 
3, 197.004, 1, 0, 0.371501,-0.0152744) , 
7, 0.0862784, 1, 0, 0.5,3.59699e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433747,-0.00530092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10575,-0.0355898) , 
7, 0.85008, 1, 0, 0.31368,-0.0506678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57418,0.0251177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547125,0.000999556) , 
6, 0.0323447, 1, 0, 0.550243,0.0137002) , 
1, 1.54564, 1, 0, 0.5,2.91555e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556893,0.00435666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257734,-0.0175497) , 
7, 1.05909, 1, 0, 0.470842,-0.00709064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.893736,0.0328945) , 
6, 3.23447, 1, 0, 0.5,1.00343e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530597,0.0206867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379196,-0.0144458) , 
6, 0.00643635, 1, 0, 0.406814,-0.0204852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687064,0.0161456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512222,-0.00874319) , 
3, 225.119, 1, 0, 0.637291,0.0302088) , 
6, 1.29379, 1, 0, 0.5,1.13584e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430246,-0.00332523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724079,0.0156974) , 
6, 1.7414, 1, 0, 0.507462,0.00620503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378922,-0.0311587) , 
7, 2.38699, 1, 0, 0.5,4.4051e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628379,0.011803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486441,-0.00433818) , 
2, -0.99005, 1, 0, 0.568596,0.01556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262721,-0.0178993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496221,0.00207192) , 
4, 4.59729, 1, 0, 0.326792,-0.0392668) , 
5, 0.253344, 1, 0, 0.5,6.56214e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974562,0.0392924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684454,0.000250263) , 
7, 0.0124487, 1, 0, 0.889562,0.0416737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47576,0.00575856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289592,-0.011956) , 
3, 169.232, 1, 0, 0.371501,-0.0137467) , 
7, 0.0862784, 1, 0, 0.5,-3.38471e-07)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740352,0.0063489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855764,0.0233208) , 
6, 0.776273, 1, 0, 0.815796,0.0439853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803483,0.0271279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374695,-0.00618286) , 
8, 301.48, 1, 0, 0.410566,-0.0124251) , 
5, -1.98537, 1, 0, 0.5,2.46397e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698823,0.0123403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299192,-0.0146497) , 
5, -8.95025, 1, 0, 0.374821,-0.0292137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643169,0.0103952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246782,-0.0145847) , 
8, 809.952, 1, 0, 0.583555,0.0195513) , 
4, 3.47175, 1, 0, 0.5,3.10631e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475917,-0.000245603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886888,0.0316843) , 
6, 2.83036, 1, 0, 0.510264,0.00683418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383651,-0.0243925) , 
7, 2.15692, 1, 0, 0.5,2.08032e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512726,0.00184133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726615,0.0231368) , 
4, 4.95092, 1, 0, 0.560357,0.0196483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.943785,0.0229822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306037,-0.0115931) , 
7, 0.0279853, 1, 0, 0.420058,-0.0259595) , 
2, -0.99005, 1, 0, 0.5,2.76662e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630411,0.02303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608901,0.00301673) , 
6, 0.0252952, 1, 0, 0.611674,0.0189588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488823,0.00626128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250296,-0.0188599) , 
3, 161.997, 1, 0, 0.347018,-0.0259051) , 
7, 0.776492, 1, 0, 0.5,2.80622e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517582,0.00226217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258504,-0.0214414) , 
7, 1.51708, 1, 0, 0.47531,-0.00524374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906853,0.0326493) , 
6, 3.39619, 1, 0, 0.5,1.68717e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531577,0.0189401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37006,-0.0150717) , 
6, 0.00547075, 1, 0, 0.402721,-0.0196261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640153,0.0110999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447778,-0.0162264) , 
3, 290.441, 1, 0, 0.611934,0.022621) , 
6, 1.09972, 1, 0, 0.5,1.76903e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471034,-0.00486816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67745,0.0122022) , 
4, 3.20508, 1, 0, 0.611441,0.018456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314713,-0.011102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535336,0.007236) , 
4, 5.09426, 1, 0, 0.355586,-0.0238976) , 
5, 0.104097, 1, 0, 0.5,8.34796e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982404,0.0422634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757759,0.00222386) , 
7, 0.00729821, 1, 0, 0.889562,0.0351127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477996,0.014283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354155,-0.00659103) , 
6, 0.0323447, 1, 0, 0.371501,-0.0115752) , 
7, 0.0862784, 1, 0, 0.5,5.15155e-06)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352005,-0.00902842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610155,0.00942353) , 
1, 1.53462, 1, 0, 0.560357,0.0174127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603636,0.000834739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236091,-0.0160524) , 
8, 489.948, 1, 0, 0.420058,-0.0229962) , 
2, -0.99005, 1, 0, 0.5,2.86463e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411029,-0.00539626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622761,0.00958081) , 
6, 1.08087, 1, 0, 0.506925,0.00478501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381006,-0.026886) , 
7, 2.41575, 1, 0, 0.5,1.92796e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507774,-0.00238343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73089,0.0134292) , 
4, 3.20508, 1, 0, 0.656278,0.0211627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750324,0.0191927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334597,-0.00770805) , 
8, 319.997, 1, 0, 0.373902,-0.0170465) , 
5, 0.0543475, 1, 0, 0.5,1.62407e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609287,0.0192403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577545,0.00183115) , 
6, 0.0252952, 1, 0, 0.5817,0.0140447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123175,-0.0240468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573411,0.00349171) , 
6, 1.39082, 1, 0, 0.351675,-0.0254543) , 
7, 0.949045, 1, 0, 0.5,1.55612e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657304,0.00601632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277822,-0.0107438) , 
7, 0.420793, 1, 0, 0.438482,-0.012074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745366,0.0165927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308379,-0.00856053) , 
8, 698.482, 1, 0, 0.646555,0.0287637) , 
4, 4.53067, 1, 0, 0.5,-4.89388e-08)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873478,0.0254956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791063,0.00939323) , 
3, 143.51, 1, 0, 0.815796,0.0342581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803483,0.0231928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374695,-0.00510695) , 
8, 301.48, 1, 0, 0.410566,-0.00970398) , 
5, -1.98537, 1, 0, 0.5,-1.58978e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501942,0.00120427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235035,-0.0227939) , 
7, 1.74607, 1, 0, 0.470842,-0.00487607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.893736,0.0261239) , 
6, 3.23447, 1, 0, 0.5,4.63657e-06)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369779,-0.00550622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629895,0.00939603) , 
1, 1.75072, 1, 0, 0.560357,0.0155602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.943785,0.0190845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306037,-0.00954504) , 
7, 0.0279853, 1, 0, 0.420058,-0.0205964) , 
2, -0.99005, 1, 0, 0.5,5.53049e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451918,-0.0039036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655797,0.012045) , 
6, 1.00269, 1, 0, 0.556949,0.0134371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874129,0.0163528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249156,-0.0129524) , 
7, 0.0862809, 1, 0, 0.405102,-0.0223766) , 
3, 207.91, 1, 0, 0.5,5.43516e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469694,-0.000696269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883677,0.0261445) , 
6, 2.82227, 1, 0, 0.506925,0.0041832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381006,-0.0247575) , 
7, 2.41575, 1, 0, 0.5,3.28126e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592549,0.0183056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565426,0.0012394) , 
6, 0.0323447, 1, 0, 0.568596,0.0107755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21334,-0.0176873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437757,-0.00195924) , 
4, 3.76725, 1, 0, 0.326792,-0.0271754) , 
5, 0.253344, 1, 0, 0.5,9.45311e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493445,0.000535745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281088,-0.0205203) , 
7, 1.52975, 1, 0, 0.457329,-0.00838181) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779603,0.0189904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340624,-0.00480137) , 
8, 653.362, 1, 0, 0.661603,0.0317611) , 
4, 4.94503, 1, 0, 0.5,3.65163e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531577,0.0151292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37006,-0.0123953) , 
6, 0.00547075, 1, 0, 0.402721,-0.0150618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640153,0.00910834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447778,-0.0145391) , 
3, 290.441, 1, 0, 0.611934,0.0173363) , 
6, 1.09972, 1, 0, 0.5,2.47568e-06)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873478,0.0231408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791063,0.00858138) , 
3, 143.51, 1, 0, 0.815796,0.0301712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803483,0.0208951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374695,-0.00458968) , 
8, 301.48, 1, 0, 0.410566,-0.00854799) , 
5, -1.98537, 1, 0, 0.5,-2.69578e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572409,0.00667471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447757,-0.0139254) , 
7, 2.04188, 1, 0, 0.560357,0.0139055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468514,-0.000557497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349947,-0.0146851) , 
0, 79.7945, 1, 0, 0.420058,-0.0184119) , 
2, -0.99005, 1, 0, 0.5,2.47361e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684366,0.0103185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295001,-0.0129303) , 
5, -8.95025, 1, 0, 0.374101,-0.022709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616343,0.00663358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232068,-0.0116925) , 
8, 828.531, 1, 0, 0.5622,0.0112185) , 
4, 3.28759, 1, 0, 0.5,-5.20853e-07)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98091,0.0386721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878001,-0.00727727) , 
7, 0.00843683, 1, 0, 0.954993,0.0299521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493715,0.0114217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363545,-0.00490843) , 
6, 0.0323447, 1, 0, 0.381925,-0.00777949) , 
7, 0.0287606, 1, 0, 0.5,-5.25457e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531316,0.0124061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36852,-0.0119313) , 
6, 0.00514936, 1, 0, 0.402761,-0.0148938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678576,0.0134892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533265,-0.00241867) , 
3, 172.623, 1, 0, 0.602804,0.0157779) , 
6, 1.03503, 1, 0, 0.5,1.53869e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472624,-0.000489628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891922,0.0249522) , 
6, 2.87219, 1, 0, 0.507732,0.00375603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37988,-0.0207851) , 
7, 2.35823, 1, 0, 0.5,1.08003e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526072,0.000758889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142395,-0.019941) , 
7, 0.485764, 1, 0, 0.31368,-0.0281476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577074,0.00426626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195554,-0.0178872) , 
8, 977.158, 1, 0, 0.550243,0.00760952) , 
1, 1.54564, 1, 0, 0.5,1.51387e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473542,-0.00125367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698439,0.00918808) , 
6, 1.29379, 1, 0, 0.568596,0.00915885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360451,-0.00481063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198073,-0.0215719) , 
7, 1.48314, 1, 0, 0.326792,-0.0231073) , 
5, 0.253344, 1, 0, 0.5,5.46249e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512726,0.00123051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726615,0.016162) , 
4, 4.95092, 1, 0, 0.560357,0.0124014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825474,0.0134849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357146,-0.00813401) , 
8, 304.881, 1, 0, 0.420058,-0.0164178) , 
2, -0.99005, 1, 0, 0.5,3.31241e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982015,0.038356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489516,0.000697564) , 
7, 0.00744157, 1, 0, 0.617168,0.012481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493596,0.0061407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261749,-0.0132564) , 
3, 156.145, 1, 0, 0.346629,-0.0163298) , 
7, 0.747733, 1, 0, 0.5,3.26201e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492823,0.000479459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224687,-0.0257716) , 
7, 2.1468, 1, 0, 0.47531,-0.0034239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906853,0.0253158) , 
6, 3.39619, 1, 0, 0.5,1.76698e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564849,0.0156888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539304,0.00200006) , 
6, 0.0323447, 1, 0, 0.542464,0.0114167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505005,-0.000683476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349947,-0.0127561) , 
2, -0.99005, 1, 0, 0.437831,-0.016672) , 
0, 79.7945, 1, 0, 0.5,1.73388e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670129,0.00743301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302748,-0.0136454) , 
5, -8.95025, 1, 0, 0.387561,-0.023809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68507,0.00737987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302986,-0.00349884) , 
8, 568.434, 1, 0, 0.537046,0.00786261) , 
4, 3.10343, 1, 0, 0.5,1.36287e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531771,0.0110403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362206,-0.0119239) , 
6, 0.00450556, 1, 0, 0.401123,-0.0139789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607788,0.00660059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404833,-0.0176858) , 
3, 332.494, 1, 0, 0.587707,0.0124184) , 
6, 0.905652, 1, 0, 0.5,9.91651e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97724,0.0337105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437657,0.00019316) , 
7, 0.0103027, 1, 0, 0.570241,0.0092758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525179,0.0071981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264464,-0.0153378) , 
3, 151.524, 1, 0, 0.354347,-0.0192205) , 
7, 1.03532, 1, 0, 0.5,4.59328e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514536,-0.01125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621751,0.00608195) , 
4, 2.37759, 1, 0, 0.611441,0.0114319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316409,-0.00755442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537752,0.00542217) , 
4, 5.13824, 1, 0, 0.355586,-0.0147764) , 
5, 0.104097, 1, 0, 0.5,1.65336e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679983,0.00334912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891187,0.023896) , 
6, 1.25561, 1, 0, 0.798367,0.0325568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.0298502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00322231) , 
8, 271.18, 1, 0, 0.454151,-0.00498749) , 
5, -8.95025, 1, 0, 0.5,1.33202e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463009,-0.000773859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858162,0.017958) , 
6, 2.64212, 1, 0, 0.506925,0.00300661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381006,-0.019171) , 
7, 2.41575, 1, 0, 0.5,1.93379e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978404,0.0328405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45017,0.000383882) , 
7, 0.00944454, 1, 0, 0.5817,0.00902385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117832,-0.0214694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503392,0.00174047) , 
6, 1.00269, 1, 0, 0.351675,-0.0163246) , 
7, 0.949045, 1, 0, 0.5,2.06628e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445618,-0.003546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621802,0.00737675) , 
6, 0.776273, 1, 0, 0.549894,0.00840821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468918,-0.00138134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140519,-0.0292973) , 
7, 1.29415, 1, 0, 0.394484,-0.0177049) , 
3, 222.455, 1, 0, 0.5,2.47049e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496588,0.000534681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281819,-0.0160345) , 
7, 1.47607, 1, 0, 0.457329,-0.00621043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779603,0.0146609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340624,-0.00274188) , 
8, 653.362, 1, 0, 0.661603,0.0235985) , 
4, 4.94503, 1, 0, 0.5,1.63705e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587789,0.00584198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415531,-0.0076752) , 
3, 288.893, 1, 0, 0.560357,0.0105107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463717,-0.0011712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335411,-0.0127444) , 
0, 89.1542, 1, 0, 0.420058,-0.0138884) , 
2, -0.99005, 1, 0, 0.5,1.41173e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492823,0.000317256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224687,-0.0216196) , 
7, 2.1468, 1, 0, 0.47531,-0.00288666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906853,0.0226835) , 
6, 3.39619, 1, 0, 0.5,1.07934e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670129,0.00634376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302748,-0.012031) , 
5, -8.95025, 1, 0, 0.387561,-0.020377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66157,0.00708146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388221,-0.00234231) , 
5, 0.104097, 1, 0, 0.537046,0.00672846) , 
4, 3.10343, 1, 0, 0.5,1.10892e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.90821,0.0277241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371316,-0.00653159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553359,0.00286178) , 
6, 0.776273, 1, 0, 0.477154,-0.00267852) , 
8, 252.602, 1, 0, 0.5,8.11884e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564849,0.0148918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539304,0.00136272) , 
6, 0.0323447, 1, 0, 0.542464,0.00931785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333807,-0.0093718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56021,0.00060097) , 
1, 2.40774, 1, 0, 0.437831,-0.013619) , 
0, 79.7945, 1, 0, 0.5,9.27656e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506189,0.000369058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13498,-0.0172773) , 
7, 0.546484, 1, 0, 0.31368,-0.0209321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57418,0.0118501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547125,0.000414835) , 
6, 0.0323447, 1, 0, 0.550243,0.00565337) , 
1, 1.54564, 1, 0, 0.5,6.92549e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868437,0.00541669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724746,0.0164661) , 
8, 356.13, 1, 0, 0.798367,0.0283839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.0265287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00282755) , 
8, 271.18, 1, 0, 0.454151,-0.00435898) , 
5, -8.95025, 1, 0, 0.5,2.29592e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512726,0.00101661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726615,0.0128435) , 
4, 4.95092, 1, 0, 0.560357,0.00945226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.832025,0.00638642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29195,-0.0068941) , 
7, 0.111936, 1, 0, 0.420058,-0.0125068) , 
2, -0.99005, 1, 0, 0.5,5.41921e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582621,0.0114425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557415,0.000700289) , 
6, 0.0323447, 1, 0, 0.560396,0.00619972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20866,-0.0133978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439245,-0.00111381) , 
4, 3.76725, 1, 0, 0.324559,-0.0179915) , 
5, 0.303093, 1, 0, 0.5,4.56626e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440132,-0.00154042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741236,0.00901665) , 
6, 1.84365, 1, 0, 0.520754,0.00385806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590238,-0.00134929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142291,-0.0209177) , 
7, 0.46015, 1, 0, 0.344644,-0.0288633) , 
3, 324.271, 1, 0, 0.5,1.86822e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975007,0.0291201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40074,-0.00105419) , 
7, 0.0121622, 1, 0, 0.506403,0.00248206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.0176618) , 
7, 2.44451, 1, 0, 0.5,-3.10062e-07)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520535,0.00117851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266772,-0.0113339) , 
7, 1.48845, 1, 0, 0.477111,-0.00241424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910168,0.0216465) , 
6, 3.46088, 1, 0, 0.5,1.10044e-05)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462059,-0.00349582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640545,0.00816264) , 
6, 0.776273, 1, 0, 0.568494,0.00973401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436559,0.0114251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421403,-0.00720262) , 
6, 0.0317621, 1, 0, 0.423243,-0.0108842) , 
3, 186.092, 1, 0, 0.5,1.13304e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909107,0.0120663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249062,-0.00909993) , 
7, 0.0438505, 1, 0, 0.387561,-0.0175063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566504,0.00337146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19058,-0.0121814) , 
8, 977.158, 1, 0, 0.537046,0.00577986) , 
4, 3.10343, 1, 0, 0.5,8.98663e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858554,0.0062804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701208,0.0163215) , 
8, 392.271, 1, 0, 0.798367,0.0259769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.02443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00259212) , 
8, 271.18, 1, 0, 0.454151,-0.0039845) , 
5, -8.95025, 1, 0, 0.5,6.29267e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564849,0.0120892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539304,0.00142557) , 
6, 0.0323447, 1, 0, 0.542464,0.00814569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505005,-0.000480528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349947,-0.00979032) , 
2, -0.99005, 1, 0, 0.437831,-0.0119051) , 
0, 79.7945, 1, 0, 0.5,8.35537e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460428,-0.00167239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107431,-0.0201053) , 
7, 0.705213, 1, 0, 0.309317,-0.0215639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546304,0.00261409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410507,-0.0143988) , 
7, 2.41575, 1, 0, 0.538019,0.00430725) , 
1, 1.40052, 1, 0, 0.5,6.45044e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51891,0.00107387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13721,-0.0136295) , 
7, 1.05186, 1, 0, 0.422181,-0.0056664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.751025,0.0086341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573723,-0.00678018) , 
3, 261.409, 1, 0, 0.717275,0.0158294) , 
6, 1.84365, 1, 0, 0.5,2.23185e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868437,0.00449062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724746,0.0145181) , 
8, 356.13, 1, 0, 0.798367,0.0241118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299192,-0.00753168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546892,0.00205911) , 
4, 3.47175, 1, 0, 0.454151,-0.00370622) , 
5, -8.95025, 1, 0, 0.5,-9.16615e-07)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621513,0.00535815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373604,-0.00367016) , 
5, 0.303034, 1, 0, 0.560357,0.00808482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603636,0.000433674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236091,-0.00877847) , 
8, 489.948, 1, 0, 0.420058,-0.0107121) , 
2, -0.99005, 1, 0, 0.5,-1.68137e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500869,0.000657245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297105,-0.0135625) , 
7, 1.52975, 1, 0, 0.465692,-0.00413014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676348,0.0123735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655576,-0.00125368) , 
1, 3.8232, 1, 0, 0.669446,0.0203805) , 
4, 5.17523, 1, 0, 0.5,-3.11014e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524245,0.00803045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457601,-0.00264088) , 
6, 0.015286, 1, 0, 0.465734,-0.00272258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877074,0.0139875) , 
6, 3.07275, 1, 0, 0.5,-3.85735e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532696,0.00872707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356923,-0.0110395) , 
6, 0.00370106, 1, 0, 0.40312,-0.0109864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636831,0.00717372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48382,-0.00268592) , 
3, 186.092, 1, 0, 0.567048,0.00759999) , 
6, 0.743928, 1, 0, 0.5,-2.0164e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975007,0.0275139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40074,-0.00100618) , 
7, 0.0121622, 1, 0, 0.506403,0.00210614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.0156697) , 
7, 2.44451, 1, 0, 0.5,-4.20025e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700175,0.00833874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408149,-0.00126026) , 
5, 0.0542902, 1, 0, 0.542464,0.00721996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53485,0.00220451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391627,-0.00715503) , 
3, 152.448, 1, 0, 0.437831,-0.010556) , 
0, 79.7945, 1, 0, 0.5,5.8325e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909107,0.00992487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249062,-0.00793923) , 
7, 0.0438505, 1, 0, 0.387561,-0.0151477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435825,-0.00151799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66836,0.00585956) , 
6, 1.39082, 1, 0, 0.537046,0.00499745) , 
4, 3.10343, 1, 0, 0.5,4.98803e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858554,0.00508944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701208,0.0143215) , 
8, 392.271, 1, 0, 0.798367,0.0217708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.0221975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00225094) , 
8, 271.18, 1, 0, 0.454151,-0.00334064) , 
5, -8.95025, 1, 0, 0.5,4.14553e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440132,-0.00111949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741236,0.00704661) , 
6, 1.84365, 1, 0, 0.520754,0.00307992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590238,-0.00135369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142291,-0.0175151) , 
7, 0.46015, 1, 0, 0.344644,-0.0230049) , 
3, 324.271, 1, 0, 0.5,5.84405e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482254,-0.000138651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930223,0.0246527) , 
6, 3.24261, 1, 0, 0.506403,0.00200097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.0149745) , 
7, 2.44451, 1, 0, 0.5,3.85628e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574786,0.00404483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450764,-0.0078353) , 
7, 1.89809, 1, 0, 0.560357,0.00733509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48304,0.00306427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394423,-0.00656421) , 
0, 47.0356, 1, 0, 0.420058,-0.00969975) , 
2, -0.99005, 1, 0, 0.5,6.65662e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434253,-8.28553e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166542,-0.0186506) , 
7, 1.34378, 1, 0, 0.378993,-0.00844601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658933,0.00471758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234854,-0.00861354) , 
8, 847.109, 1, 0, 0.613332,0.00792038) , 
1, 2.27122, 1, 0, 0.5,5.18644e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493173,-0.0109601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566417,0.00308468) , 
4, 2.36679, 1, 0, 0.560396,0.00473558) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320894,-0.00797858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332738,0.000968225) , 
5, 0.836722, 1, 0, 0.324559,-0.0137504) , 
5, 0.303093, 1, 0, 0.5,1.48764e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679983,0.00103102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891187,0.0177793) , 
6, 1.25561, 1, 0, 0.798367,0.0200807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.0205642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00207683) , 
8, 271.18, 1, 0, 0.454151,-0.00308525) , 
5, -8.95025, 1, 0, 0.5,3.9902e-07)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584963,0.00222395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298046,-0.00664425) , 
7, 0.778294, 1, 0, 0.465692,-0.0035762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67344,0.0135793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66644,0.00188016) , 
1, 3.43572, 1, 0, 0.669446,0.0176855) , 
4, 5.17523, 1, 0, 0.5,3.78739e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670129,0.00403628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302748,-0.00851345) , 
5, -8.95025, 1, 0, 0.387561,-0.0134633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435313,-0.00133029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664229,0.00511257) , 
6, 1.35848, 1, 0, 0.537046,0.00443935) , 
4, 3.10343, 1, 0, 0.5,2.63352e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450184,-0.00207947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644978,0.00558652) , 
6, 0.905652, 1, 0, 0.556949,0.00589922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454365,-0.00115383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155893,-0.0232661) , 
7, 1.55298, 1, 0, 0.405102,-0.00982606) , 
3, 207.91, 1, 0, 0.5,1.55666e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347085,-0.00558358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596672,0.00393399) , 
1, 1.36654, 1, 0, 0.560357,0.00662573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48304,0.00276491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394423,-0.00599257) , 
0, 47.0356, 1, 0, 0.420058,-0.00877789) , 
2, -0.99005, 1, 0, 0.5,-9.4755e-07)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522411,0.0071309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471916,-0.00202389) , 
6, 0.0173756, 1, 0, 0.477915,-0.00171031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911721,0.0176008) , 
6, 3.49323, 1, 0, 0.5,-1.58072e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975009,0.0256314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401554,-0.000912712) , 
7, 0.0120197, 1, 0, 0.506925,0.00180311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381006,-0.0132043) , 
7, 2.41575, 1, 0, 0.5,6.13266e-08)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419529,-0.00283527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593022,0.00368816) , 
6, 0.776273, 1, 0, 0.520754,0.0026845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590238,-0.00178726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142291,-0.0153117) , 
7, 0.46015, 1, 0, 0.344644,-0.0200273) , 
3, 324.271, 1, 0, 0.5,7.93162e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535193,0.00748937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516301,-0.000239606) , 
6, 0.0323447, 1, 0, 0.518576,0.00243528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335202,-0.00800317) , 
0, 149.992, 1, 0, 0.5,5.45125e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504445,-0.0103865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598405,0.00355793) , 
4, 2.37588, 1, 0, 0.589938,0.00547869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214997,-0.00927295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424093,-0.000746886) , 
1, 1.98896, 1, 0, 0.343475,-0.00952283) , 
5, 0.153846, 1, 0, 0.5,4.42841e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858554,0.00381976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701208,0.0126419) , 
8, 392.271, 1, 0, 0.798367,0.0179932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.0191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00189101) , 
8, 271.18, 1, 0, 0.454151,-0.00276173) , 
5, -8.95025, 1, 0, 0.5,2.77418e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564849,0.00956835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539304,0.000890493) , 
6, 0.0323447, 1, 0, 0.542464,0.00572132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53485,0.00188974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391627,-0.00590058) , 
3, 152.448, 1, 0, 0.437831,-0.00836646) , 
0, 79.7945, 1, 0, 0.5,4.00285e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491736,0.000288934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312728,-0.0135089) , 
7, 1.8518, 1, 0, 0.471476,-0.00280242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880651,0.0186141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463682,0.000210134) , 
8, 489.926, 1, 0, 0.673631,0.0170812) , 
4, 5.35939, 1, 0, 0.5,3.11598e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511162,0.000603013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724147,0.0086744) , 
4, 4.90493, 1, 0, 0.560357,0.00602274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807506,0.00370979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288569,-0.0047926) , 
7, 0.13992, 1, 0, 0.420058,-0.00796831) , 
2, -0.99005, 1, 0, 0.5,3.75321e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495053,0.00022558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237212,-0.0136492) , 
7, 2.1468, 1, 0, 0.477915,-0.00156973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911721,0.0165828) , 
6, 3.49323, 1, 0, 0.5,3.18893e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532696,0.00770606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356923,-0.00912413) , 
6, 0.00370106, 1, 0, 0.40312,-0.00812814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48771,-0.0114676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574645,0.00346225) , 
4, 2.68907, 1, 0, 0.567048,0.00563141) , 
6, 0.743928, 1, 0, 0.5,3.61477e-06)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868437,0.00263116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724746,0.0115463) , 
8, 356.13, 1, 0, 0.798367,0.017507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236957,-0.00987289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491501,0.000297868) , 
1, 1.37633, 1, 0, 0.454151,-0.00268858) , 
5, -8.95025, 1, 0, 0.5,1.4304e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471743,-0.00378357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610442,0.00507542) , 
6, 0.517515, 1, 0, 0.568494,0.00623074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436559,0.0090311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421403,-0.00522349) , 
6, 0.0317621, 1, 0, 0.423243,-0.00698114) , 
3, 186.092, 1, 0, 0.5,5.67872e-07)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9828,0.0322907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561288,0.000183551) , 
7, 0.00515235, 1, 0, 0.67132,0.00701292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167582,-0.00904388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512658,0.00241196) , 
6, 1.09972, 1, 0, 0.348143,-0.00621665) , 
7, 0.517662, 1, 0, 0.5,-2.42136e-07)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975007,0.0232279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40074,-0.000771713) , 
7, 0.0121622, 1, 0, 0.506403,0.00154129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.012158) , 
7, 2.44451, 1, 0, 0.5,5.95267e-06)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441379,-0.00278416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590936,0.00357529) , 
6, 0.582205, 1, 0, 0.540786,0.00375963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457961,-0.000848867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119266,-0.0237935) , 
7, 1.29415, 1, 0, 0.381083,-0.010917) , 
3, 244.273, 1, 0, 0.5,1.14499e-05)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734973,0.00632528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434476,-0.00136222) , 
5, 0.025344, 1, 0, 0.560396,0.00369203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320894,-0.0068245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332738,0.00168529) , 
5, 0.836722, 1, 0, 0.324559,-0.0106952) , 
5, 0.303093, 1, 0, 0.5,7.59788e-06)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587789,0.00334323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415531,-0.0048456) , 
3, 288.893, 1, 0, 0.560357,0.00544902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48304,0.00249671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394423,-0.00512504) , 
0, 47.0356, 1, 0, 0.420058,-0.00720162) , 
2, -0.99005, 1, 0, 0.5,6.6829e-06)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462702,-0.00899406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830379,0.0108935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458129,-0.000432281) , 
5, -8.95025, 1, 0, 0.502453,0.00158026) , 
4, 2.22867, 1, 0, 0.5,5.48948e-06)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.90821,0.0180132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371056,-0.00402113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549587,0.00166367) , 
6, 0.743928, 1, 0, 0.477154,-0.00144769) , 
8, 252.602, 1, 0, 0.5,5.58319e-06)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470838,-0.000380064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.892261,0.0142346) , 
6, 2.88232, 1, 0, 0.506403,0.00140731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.0112104) , 
7, 2.44451, 1, 0, 0.5,5.75415e-06)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564849,0.00910816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539304,0.000627535) , 
6, 0.0323447, 1, 0, 0.542464,0.00491601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333807,-0.00563449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56021,0.000569322) , 
1, 2.40774, 1, 0, 0.437831,-0.00718076) , 
0, 79.7945, 1, 0, 0.5,6.7081e-06)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795066,0.00386026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229955,-0.00633403) , 
7, 0.131531, 1, 0, 0.387561,-0.0101369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566504,0.00208981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19058,-0.00787883) , 
8, 977.158, 1, 0, 0.537046,0.00334731) , 
4, 3.10343, 1, 0, 0.5,5.60638e-06)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609287,0.00782295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577545,0.000397577) , 
6, 0.0252952, 1, 0, 0.5817,0.00429511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51695,0.00611347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265848,-0.00898174) , 
3, 151.524, 1, 0, 0.351675,-0.00778638) , 
7, 0.949045, 1, 0, 0.5,4.04709e-06)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522411,0.0053989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471916,-0.00158647) , 
6, 0.0173756, 1, 0, 0.477915,-0.00134728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911721,0.0147913) , 
6, 3.49323, 1, 0, 0.5,2.48968e-06)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511162,0.000438283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724147,0.00755931) , 
4, 4.90493, 1, 0, 0.560357,0.00495762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73086,0.00277989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305061,-0.00444662) , 
8, 372.178, 1, 0, 0.420058,-0.00655874) , 
2, -0.99005, 1, 0, 0.5,3.25131e-06)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487533,-0.0101427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55903,0.00213852) , 
4, 2.22867, 1, 0, 0.554185,0.00309544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316765,-0.00693396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331626,0.00173895) , 
5, 0.84193, 1, 0, 0.321728,-0.0101725) , 
5, 0.352843, 1, 0, 0.5,2.72764e-06)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975009,0.0217031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401554,-0.000712264) , 
7, 0.0120197, 1, 0, 0.506925,0.00133698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381006,-0.010278) , 
7, 2.41575, 1, 0, 0.5,1.82857e-06)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440132,-0.000879656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741236,0.00516423) , 
6, 1.84365, 1, 0, 0.520754,0.00203303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590238,-0.00187852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142291,-0.0118679) , 
7, 0.46015, 1, 0, 0.344644,-0.0151609) , 
3, 324.271, 1, 0, 0.5,6.73876e-06)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535193,0.00551671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516301,-0.000140247) , 
6, 0.0323447, 1, 0, 0.518576,0.00183879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335202,-0.00626453) , 
0, 149.992, 1, 0, 0.5,5.52702e-06)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868437,0.00070914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724746,0.0102292) , 
8, 356.13, 1, 0, 0.798367,0.0137807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862055,0.0123943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413742,-0.00165885) , 
8, 289.759, 1, 0, 0.454151,-0.0021122) , 
5, -8.95025, 1, 0, 0.5,4.69922e-06)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458121,-0.000777794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102345,-0.0152593) , 
7, 0.705213, 1, 0, 0.308117,-0.0134097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586318,0.00223541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346418,-0.00340589) , 
5, 0.352843, 1, 0, 0.531161,0.00218355) , 
1, 1.30378, 1, 0, 0.5,5.06954e-06)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505932,0.000648828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308911,-0.00921037) , 
7, 1.52975, 1, 0, 0.471476,-0.00215852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880651,0.0158194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463682,-0.000243244) , 
8, 489.926, 1, 0, 0.673631,0.0131607) , 
4, 5.35939, 1, 0, 0.5,2.98262e-06)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525691,0.00536352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440659,-0.00201121) , 
6, 0.0131948, 1, 0, 0.451504,-0.0020265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764719,-0.00107046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.884446,0.0150041) , 
1, 2.72888, 1, 0, 0.826947,0.0136873) , 
6, 2.65227, 1, 0, 0.5,3.26823e-06)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574786,0.00265885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450764,-0.00571153) , 
7, 1.89809, 1, 0, 0.560357,0.00451251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506048,0.000971535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357099,-0.00543094) , 
3, 169.068, 1, 0, 0.420058,-0.00596702) , 
2, -0.99005, 1, 0, 0.5,4.18944e-06)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532741,0.00587775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35512,-0.00791197) , 
6, 0.00337876, 1, 0, 0.404976,-0.00666043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476798,-0.00900105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56762,0.00276533) , 
4, 2.73511, 1, 0, 0.558848,0.00413014) , 
6, 0.679239, 1, 0, 0.5,3.31522e-06)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858554,0.00247431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701208,0.010436) , 
8, 392.271, 1, 0, 0.798367,0.0135962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299192,-0.00446742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546892,0.00115721) , 
4, 3.47175, 1, 0, 0.454151,-0.00208728) , 
5, -8.95025, 1, 0, 0.5,1.72502e-06)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975007,0.0206968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40074,-0.000681158) , 
7, 0.0121622, 1, 0, 0.506403,0.00120736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.00992799) , 
7, 2.44451, 1, 0, 0.5,1.26766e-06)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560649,0.00104992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278693,-0.0042338) , 
7, 1.05909, 1, 0, 0.477915,-0.00114898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911721,0.0130906) , 
6, 3.49323, 1, 0, 0.5,5.67428e-06)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440132,-0.000786432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741236,0.00467007) , 
6, 1.84365, 1, 0, 0.520754,0.00183236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243758,-0.0111959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444851,-0.00206891) , 
1, 2.25485, 1, 0, 0.344644,-0.0136682) , 
3, 324.271, 1, 0, 0.5,5.63564e-06)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703704,0.0048974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335361,-0.00169998) , 
8, 478.845, 1, 0, 0.542464,0.00410209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47956,-0.000673552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32463,-0.00777662) , 
3, 249.222, 1, 0, 0.437831,-0.00599379) , 
0, 79.7945, 1, 0, 0.5,4.82466e-06)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.90821,0.0149744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371056,-0.00371366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549587,0.001636) , 
6, 0.743928, 1, 0, 0.477154,-0.00114367) , 
8, 252.602, 1, 0, 0.5,4.08628e-06)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476684,-0.000194038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911497,0.0140597) , 
6, 3.06246, 1, 0, 0.506403,0.001156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38439,-0.00957096) , 
7, 2.44451, 1, 0, 0.5,4.09456e-06)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514536,-0.00754379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621751,0.0028946) , 
4, 2.37759, 1, 0, 0.611441,0.00420909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661533,0.00585299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30207,-0.00348204) , 
8, 357.033, 1, 0, 0.355586,-0.00544333) , 
5, 0.104097, 1, 0, 0.5,4.86355e-06)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472163,1.51042e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727177,0.00541235) , 
1, 2.80722, 1, 0, 0.560357,0.00414316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48304,0.0022818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394423,-0.00415747) , 
0, 47.0356, 1, 0, 0.420058,-0.0054781) , 
2, -0.99005, 1, 0, 0.5,4.06755e-06)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868437,0.000515743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724746,0.00914448) , 
8, 356.13, 1, 0, 0.798367,0.0120302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471434,0.000159543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321195,-0.00856693) , 
7, 1.89809, 1, 0, 0.454151,-0.00184453) , 
5, -8.95025, 1, 0, 0.5,3.55118e-06)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982015,0.0263922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489516,-0.000248684) , 
7, 0.00744157, 1, 0, 0.617168,0.00392637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525971,0.00765963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30453,-0.00470411) , 
3, 132.735, 1, 0, 0.346629,-0.00513224) , 
7, 0.747733, 1, 0, 0.5,3.15919e-06)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309842,-0.00589973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510739,0.00107132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667853,-0.00885073) , 
1, 4.05744, 1, 0, 0.51951,0.00145591) , 
1, 1.11029, 1, 0, 0.5,8.07363e-06)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505932,0.000523326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308911,-0.00780973) , 
7, 1.52975, 1, 0, 0.471476,-0.00183225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680934,0.0115302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669144,0.000475075) , 
1, 3.43221, 1, 0, 0.673631,0.0112036) , 
4, 5.35939, 1, 0, 0.5,7.08123e-06)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564738,0.00728935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513099,-0.000150511) , 
0, 24.8237, 1, 0, 0.518576,0.00149355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335202,-0.00519592) , 
0, 149.992, 1, 0, 0.5,6.10199e-06)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471743,-0.00339165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610442,0.00381172) , 
6, 0.517515, 1, 0, 0.568494,0.00411784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436559,0.00848537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421403,-0.00411909) , 
6, 0.0317621, 1, 0, 0.423243,-0.00460345) , 
3, 186.092, 1, 0, 0.5,5.24577e-06)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858554,0.00159489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701208,0.00914269) , 
8, 392.271, 1, 0, 0.798367,0.0111528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885671,0.0139348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425146,-0.00126584) , 
8, 271.18, 1, 0, 0.454151,-0.00170897) , 
5, -8.95025, 1, 0, 0.5,4.18722e-06)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670129,0.00263017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302748,-0.00546355) , 
5, -8.95025, 1, 0, 0.387561,-0.00791442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435825,-0.00105281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66836,0.00351712) , 
6, 1.39082, 1, 0, 0.537046,0.00261357) , 
4, 3.10343, 1, 0, 0.5,4.48364e-06)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462702,-0.00660554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668729,0.00328981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375101,-0.00143656) , 
5, 0.0543475, 1, 0, 0.502453,0.00111872) , 
4, 2.22867, 1, 0, 0.5,3.72495e-06)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52447,0.000798044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909781,0.0126792) , 
6, 3.07275, 1, 0, 0.560357,0.00378637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48304,0.00184146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394423,-0.00372795) , 
0, 47.0356, 1, 0, 0.420058,-0.00500734) , 
2, -0.99005, 1, 0, 0.5,3.29559e-06)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984418,0.0298304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531337,6.79534e-05) , 
7, 0.00386411, 1, 0, 0.611674,0.00360104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296489,-0.00443598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568765,0.00734211) , 
4, 5.13485, 1, 0, 0.347018,-0.00492466) , 
7, 0.776492, 1, 0, 0.5,3.54259e-06)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416829,-0.00182936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590764,0.00221708) , 
6, 0.776273, 1, 0, 0.518179,0.00143019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341134,-0.00587918) , 
3, 338.816, 1, 0, 0.5,7.8567e-06)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469694,-0.000258665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883677,0.00979766) , 
6, 2.82227, 1, 0, 0.506925,0.00103824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381006,-0.00829529) , 
7, 2.41575, 1, 0, 0.5,6.81316e-06)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.90821,0.0131256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780576,0.00570377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43524,-0.00111984) , 
5, -8.95025, 1, 0, 0.477154,-0.000970075) , 
8, 252.602, 1, 0, 0.5,6.83236e-06)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453764,-0.00071458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667054,0.00581358) , 
4, 4.96705, 1, 0, 0.491181,0.000946544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666816,-0.00841461) , 
1, 4.06099, 1, 0, 0.5,6.82957e-06)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641239,0.00988487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554589,0.000170722) , 
0, 25.2566, 1, 0, 0.563239,0.00272171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531509,0.00607366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264785,-0.00838709) , 
3, 151.524, 1, 0, 0.357235,-0.00612402) , 
7, 1.09284, 1, 0, 0.5,6.24707e-06)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462702,-0.00614669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597036,0.00209862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343849,-0.00222859) , 
5, 0.153846, 1, 0, 0.502453,0.0010342) , 
4, 2.22867, 1, 0, 0.5,4.77807e-06)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587789,0.00224589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415531,-0.00348573) , 
3, 288.893, 1, 0, 0.560357,0.00346338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501733,0.00057721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350983,-0.00451002) , 
3, 175.125, 1, 0, 0.420058,-0.0045776) , 
2, -0.99005, 1, 0, 0.5,4.12978e-06)    );
   return;
};

// Clean up
inline void Readall_SR__tZq::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double Readall_SR__tZq::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
